# from https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/prometheus-install/strimzi-pod-monitor.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-operator-metrics
  namespace: {{ kafka.operator_namespace }}
  labels:
    app: strimzi
    {{ prometheus_podmonitor_label_name }}: {{ prometheus_podmonitor_labels.kafka }}
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - {{ kafka.operator_namespace }}
  podMetricsEndpoints:
  - path: /metrics
    port: http
