---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ DUNE_runcounter.namespace }}

resources:
  - runregistry-rest.yaml # https://github.com/DUNE-DAQ/microservices/blob/develop/runregistry-rest/kubernetes.yaml
