---
deployments:
  - path: namespace
    alwaysDeploy: true

  - barrier: true
    message: We need a namespace to deploy into

  - path: kube-prometheus-stack
    waitReadiness: true
    tags:
      - metrics
      - monitoring
      - alertmanager
      - prometheus
      - prometheus-operator

  - barrier: true
    message: Prometheus Operator starting (about 2m)

  - path: alertmanagers
    tags:
      - metrics
      - monitoring
      - prometheus
      - alertmanager

  - path: prometheis
    tags:
      - metrics
      - monitoring
      - prometheus
      - alertmanager

vars:
  - file: variables/alertmanager.yaml
  - file: variables/prometheus.yaml
