# from https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/kafka-cruise-control-metrics.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cruise-control-metrics
  namespace: {{ kafka.namespace }}
  labels:
    app: strimzi
data:
  metrics-config.yml: |
    # See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus Exporter metrics
    lowercaseOutputName: true
    rules:
    - pattern: kafka.cruisecontrol<name=(.+)><>(\w+)
      name: kafka_cruisecontrol_$1_$2
      type: GAUGE
