---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ DUNE_kafka.namespace }}

resources:
  - cluster-operator-metrics.yaml # https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/prometheus-install/strimzi-pod-monitor.yaml
  - entity-operator-metrics.yaml # https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/prometheus-install/strimzi-pod-monitor.yaml
  - kafka-resources-metrics.yaml # https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/prometheus-install/strimzi-pod-monitor.yaml
  - jmx-exporter-kafka.yaml # https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/kafka-metrics.yaml
