---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bridge-metrics.yaml
  - entity-operator-metrics.yaml
  - jmx-exporter-kafka.yaml
  - jmx-exporter-cruise-control.yaml
  - jmx-exporter-kafka-connect.yaml
{% if not args.with_kafka_kraft %}
  - jmx-exporter-zookeeper.yaml
{% endif %}
  - kafka-resources-metrics.yaml
