---
resources: # this is guess work
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 20m
    memory: 16Mi

nodePathMap: {{ local_path_provisioner.nodePathMap | tojson }}

storageClass:
  name: {{ local_path_provisioner.storage_class_name }}
  defaultClass: {{ local_path_provisioner.is_default_class }}
  reclaimPolicy: Retain

affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: {{ kubernetes_label.worker }}
         operator: Exists
