apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-rendered.yaml

commonLabels:
  app.kubernetes.io/component: {{ local_path_provisioner_component_value }}
  app.kubernetes.io/instance: {{ local_path_provisioner_component_value }}
