---
deployments:
  - path: namespace
    alwaysDeploy: true

  - barrier: true
    message: We need a namespace to deploy into
    waitReadinessObjects:
      - kind: Namespace

  - include: database

  - path: runnumber-rest
  - path: runregistry-rest

vars:
  - file: variables/runservices.yaml
