---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ prometheus_operator_namespace }}
  labels: # https://github.com/prometheus-operator/kube-prometheus/issues/1923
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
