---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express
  namespace: {{ DUNE_daqconfig.namespace }}
  labels:
    app.kubernetes.io/app: mongodb-express
    app.kubernetes.io/component: mongodb-express
    app.kubernetes.io/instance: mongodb-express
spec:
  selector:
    app.kubernetes.io/app: mongodb-express
    app.kubernetes.io/component: mongodb-express
    app.kubernetes.io/instance: mongodb-express
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: mongo-express
