---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ DUNE_runservices.namespace }}

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: runnum-table-sql
    files: [ sql/runnum_table.sql ] # from https://github.com/DUNE-DAQ/microservices/blob/develop/runnumber-rest/runnum_table.sql
