---
admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

serviceMonitor:
  enabled: true
  labels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}

networkPolicy:
  enabled: true

useStatefulSet: true

persistence:
  enabled: false
  inMemory:
    enabled: true    # use EmptyDir
    sizeLimit: 300Mi # this is guess work

initChownData:
  enabled: false

grafana.ini:
{% if grafana.home_dashboard_path %}
  dashboards:
    default_home_dashboard_path: {{ grafana.home_dashboard_path }}
{% else %}
  dashboards: {}
{% endif %}
{% if smtp_server.address %}
  smtp:
    enabled: true
    host: {{ smtp_server.address }}:{{ smtp_server.port }}
  emails:
    welcome_email_on_sign_up: false
{% else %}
  smtp:
    enabled: false
{% endif %}
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
    temp_data_lifetime: 12h
  server:
    enable_gzip: true
  database:
    log_queries: false
    wal: true # wal for sqlite only
    query_retries: 5 # query_retries for sqlite only
  analytics:
    check_for_updates: true
    check_for_plugin_updates: true
    reporting_enabled: false
  auth:
    login_maximum_inactive_lifetime_duration: 13h
    login_maximum_lifetime_duration: 10d
{% if 'pocket' in target.name %}
    login_cookie_name: "grafana_session_pocket_main"
{% else %}
    login_cookie_name: "grafana_session_{{ target.name }}_main"
{% endif %}
  auth.anonymous:
    enabled: true # make sure to clean your cookies or else!
    org_role: Viewer
    org_name: Main Org.
    hide_version: true
  security:
{% if 'pocket' in target.name %}
    admin_email: root@pocket
{% else %}
    admin_email: root@{{ target.name }}
{% endif %}
    disable_gravatar: true
  users:
    allow_sign_up: false
    allow_org_create: false
    default_theme: light
  log:
    mode: console

resources: # this is guess work
 limits:
   cpu: 1
   memory: 4Gi
 requests:
   cpu: 100m
   memory: 128Mi

# try not to schedule on same node as alertmanager/prometheus
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ kubernetes_labels.node_worker }}
          operator: Exists
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: alertmanager
              operator: Exists
          topologyKey: kubernetes.io/hostname
      - weight: 20
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: prometheus
              operator: Exists
          topologyKey: kubernetes.io/hostname

podDisruptionBudget:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow

service:
  labels:
    grafana: grafana

sidecar: # this is guess work
  resources:
    limits:
      cpu: 200m
      memory: 384Mi # initial maps are all in memory
    requests:
      cpu: 50m
      memory: 256Mi

  alerts:
    enabled: true
    label: "{{ grafana_alert_label_name }}"
    labelValue: "{{ grafana_alert_label_value }}"
    searchNamespace: ALL
  dashboards:
    enabled: true
    label: "{{ grafana_dashboard_label_name }}"
    labelValue: "{{ grafana_dashboard_label_value }}"
    searchNamespace: ALL
    folderAnnotation: {{ grafana_dashboard_folder_annotation }}
    provider:
      allowUiUpdates: false
      disableDelete: true
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    label: "{{ grafana_datasource_label_name }}"
    labelValue: "{{ grafana_datasource_label_value }}"
    searchNamespace: ALL
