helmChart:
  chartName: grafana
  chartVersion: 9.2.10
  namespace: '{{ monitoring.namespace }}'
  output: helm-rendered.yaml
  releaseName: grafana
  repo: https://grafana.github.io/helm-charts
  updateConstraints: ~9.x
