---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ strimzi.namespace }}

resources:
  - helm-rendered.yaml

patches:
  - target:
      kind: ConfigMap
     # not useful dashboards for us, some dashboards are left in for possible use later on
      name: '(strimzi-kafka-bridge|strimzi-kafka-connect|strimzi-kafka-mirror-maker-2|strimzi-kafka-oauth|strimzi-zookeeper)'
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
