---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ DUNE_runservices.namespace }}

resources:
  - runregistry-rest-deployment.yaml

patches:
  - target:
      kind: Namespace
    patch: |-
      $patch: delete
      kind: Kustomization
      metadata:
        name: DOES NOT MATTER
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: {{ dunedaq.unified_microservices.image }}:{{ dunedaq.unified_microservices.tag }}
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0/key
        value: {{ kubernetes_label.worker }}
{% if  with_dune_runservices_db_as == 'oracle' %}
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
        value: runservices-oracle-svcbind-custom-user
{% endif %}
