---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
  name: runregistry-rest
  namespace: {{ DUNE_runservices.namespace }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/app: runregistry-rest
      app.kubernetes.io/component: runregistry-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/app: runregistry-rest
        app.kubernetes.io/component: runregistry-rest
    spec:
      containers:
      - image: ghcr.io/dune-daq/pocket-runregistry-rest:0.8 # this tag is different than standard
        name: runregistry-rest
        env:
        - name: MICROSERVICE
          value: runregistry-rest
        envFrom:
        - secretRef:
            name: run-db-secret
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 11000
