---
# You must still deploy your database with its manifests from upstream
# and create a secret called runservices-postgresql-svcbind-custom-user
#   containing keys: host, port, dbname,  username, password
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
  name: runregistry-rest
  namespace: runservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: runregistry-rest
      app.kubernetes.io/component: runregistry-rest
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/app: runregistry-rest
        app.kubernetes.io/component: runregistry-rest
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: {{ kubernetes_label.worker }}
               operator: Exists
      containers:
      - env:
        - name: MICROSERVICE
          value: runregistry-rest
        - name: RGDB
          value: postgres
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: runservices-postgresql-svcbind-custom-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: runservices-postgresql-svcbind-custom-user
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: host
              name: runservices-postgresql-svcbind-custom-user
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: runservices-postgresql-svcbind-custom-user
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: database
              name: runservices-postgresql-svcbind-custom-user
        image: ghcr.io/dune-daq/pocket-runregistry-rest:v0.0.8
        name: runregistry-rest
        ports:
        - containerPort: 5005
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          runAsNonRoot: true
          runAsUser: 11000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /uploads
          name: uploads-volume
      volumes: # persistance is not required at this time
      - name: uploads-volume
        emptyDir:
          sizeLimit: 20Gi
      securityContext:
        fsGroup: 11000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
  name: runregistry-rest
  namespace: runservices
spec:
  ports:
  - name: http
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
  type: ClusterIP
