---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  name: grafana-server-nodeport
  namespace: monitoring
spec:
  ports:
  - name: service
    nodePort: 31003
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  type: NodePort
