---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana-devel
    app.kubernetes.io/name: grafana
  name: grafana-devel-nodeport
  namespace: monitoring
spec:
  ports:
  - name: service
    protocol: TCP
    port: 80
    targetPort: service
    nodePort: 31023
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana-devel
    app.kubernetes.io/name: grafana
  type: NodePort
