--- 
apiVersion: v1
kind: Service
metadata:    
  name: runregistry-rest-nodeport
  labels:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
  namespace: runcounter
spec:
  type: NodePort
  ports:
  - name: http
    port: 5005
    protocol: TCP
    targetPort: 5005
    nodePort: 30005
  selector:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
    app.kubernetes.io/instance: {{ target.name }}
