---
deployments:
  - path: namespace
    alwaysDeploy: true
    skipDeleteIfTags: true
    tags:
      - storage

  - barrier: true

  - path: local-path-provisioner
    skipDeleteIfTags: true
    tags:
      - storage

vars:
  - file: variables/local_path_provisioner.yaml
