---
deployments:
  - path: namespace
    alwaysDeploy: true
    skipDeleteIfTags: true
    tags:
      - storage

  - barrier: true

  - path: local-path-provisioner
    skipDeleteIfTags: true
    tags:
      - storage
