---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ DUNE_daqconfig.namespace }}
  labels: # I'd love to be restricted
    # https://github.com/bitnami/charts/pull/17236
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
