{% if with_dune_daq_services %}
{% if with_dune_daqconfig %}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  name: mongodb-nodeport
  namespace: daqconfig
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: mongodb
    nodePort: 31007
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  type: NodePort
{% endif %}
{% endif %}
