---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: ers
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: ers-database-rw
  name: ers-postgresql-nodeport
  namespace: ers
spec:
  type: NodePort
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    cnpg.io/cluster: ers-database
    cnpg.io/instanceRole: primary
