{% if with_grafana %}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana-main
    app.kubernetes.io/name: grafana
  name: grafana-server-nodeport
  namespace: monitoring
spec:
  ports:
  - name: service
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 31003
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana-main
    app.kubernetes.io/name: grafana
  type: NodePort
{% endif %}
