{% if with_dune_daq_services %}
{% if with_dune_runservices %}
--- 
apiVersion: v1
kind: Service
metadata:    
  name: runregistry-rest-nodeport
  labels:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
  namespace: runservices
spec:
  type: NodePort
  ports:
  - name: http
    port: 5005
    protocol: TCP
    targetPort: 5005
    nodePort: 30015
  selector:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
{% endif %}
{% endif %}
