---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: microsocks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: microsocks
    app.kubernetes.io/component: microsocks
  name: microsocks
  namespace: microsocks
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/app: microsocks
      app.kubernetes.io/component: microsocks
  template:
    metadata:
      labels:
        app.kubernetes.io/app: microsocks
        app.kubernetes.io/component: microsocks
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ kubernetes_label.worker }}
                operator: Exists
      containers:
      - image: ghcr.io/dune-daq/microsocks:latest
        imagePullPolicy: Always
        name: microsocks
        ports:
        - containerPort: 1080
          name: socks5
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 8Mi
            cpu: 100m
        securityContext:
          runAsUser: 10000
          runAsGroup: 10000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 10000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: microsocks
    app.kubernetes.io/component: microsocks
  name: microsocks
  namespace: microsocks
spec:
  ports:
  - name: socks5
    protocol: TCP
    port: 1080 # 1080 is the ICANN socks5 port
    targetPort: 1080
  selector:
    app.kubernetes.io/app: microsocks
    app.kubernetes.io/component: microsocks
  type: ClusterIP
