---
discriminator: "dune-daq-{{ target.name }}"

args:
  - name: in_pocket
    default: false

  ### This should be customized as an argument for your needs
  ### Since `pocket` mode is for local development of services
  ### on node local ephemeral non-exposed containers, default passwords
  ### are acceptable.
  ###
  ### For real deployments you must set these to the correct values.
  ### If you don't this should hopefully error out with random values.
  ###
  ### see: kluctl deploy -t target --args-from-file=filename.yaml
  - name: grafana_admin_password
    default: run4evah
  - name: daqconfig_mongodb_daqconfig_password
    default: run4evah
  - name: daqconfig_mongodb_root_password
    default: run4evah
  - name: ers_postgresql_password
    default: run4evah
  - name: opmon_influxdb_user_influxdb_password
    default: run4evah
  - name: opmon_influxdb_readwrite_password
    default: run4evah
  - name: opmon_influxdb_admin_password
    default: run4evah
  - name: runservices_postgresql_password
    default: run4evah
  - name: elisa_logbook_username
    default: username
  - name: elisa_logbook_password
    default: password

targets:
  - name: pocket
    context: kind-pocketdune
    args:
      in_pocket: true

  - name: pocket-baseline
    context: kind-pocketdune
    args:
      in_pocket: true

  - name: pocket-connectionservice
    discriminator: "dune-daq-pocket"
    args:
      in_pocket: true

  - name: pocket-daqconfig
    discriminator: "dune-daq-pocket"
    args:
      in_pocket: true

  - name: pocket-ers
    discriminator: "dune-daq-pocket"
    args:
      in_pocket: true

  - name: pocket-opmon
    discriminator: "dune-daq-pocket"
    args:
      in_pocket: true

  - name: pocket-runservices
    discriminator: "dune-daq-pocket"
    args:
      in_pocket: true

  - name: iceberg-services
    discriminator: "dune-daq-pocket"
    args:
      in_pocket: true

  - name: np04-services
    context: kubernetes-admin@np04-services
    args:
      # if you don't set the args to override, you get random values
      grafana_admin_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      daqconfig_mongodb_root_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      daqconfig_mongodb_daqconfig_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      ers_postgresql_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      opmon_influxdb_user_influxdb_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      opmon_influxdb_readwrite_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      opmon_influxdb_admin_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      runservices_postgresql_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      elisa_logbook_username: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      elisa_logbook_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"

  - name: np04-daq
    context: kubernetes-admin@np04-daq
    args:
      # if you don't set the args to override, you get random values
      grafana_admin_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      daqconfig_mongodb_root_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      daqconfig_mongodb_daqconfig_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      ers_postgresql_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      opmon_influxdb_user_influxdb_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      opmon_influxdb_readwrite_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      opmon_influxdb_admin_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      runservices_postgresql_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      elisa_logbook_username: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
      elisa_logbook_password: "{{ '{:0=13}'.format(range(0, 9999999999999) | random) | string }}"
