---
discriminator: "dune-daq-{{ target.name }}"

args:
  - name: with_cilium
    default: true
  - name: with_cvmfs_csi
    default: true
  - name: with_dns_autoscaler
    default: true
  - name: with_dune_daq
    default: true
  - name: with_grafana
    default: true
  - name: with_kepler
    default: true
  - name: with_kubernetes_dashboard
    default: true
  - name: with_nfs_storage
    default: false # changeme when finished with layout
  - name: with_node_feature_discovery
    default: true
  - name: with_node_problem_detector
    default: false
  - name: with_operators
    default: true
  - name: with_trivy
    default: false
  - name: with_kafka_kraft
    default: false
  - name: with_local_path_as_default_storageclass
    default: false

  ### This should be customized as an argument for your needs
  ### FIXME:
  ### these should probably lose the default for non-pocket
  ### users and thus force folks to set a specific password
  ### to increase the chances that these are secure in production
  - name: grafana_admin_password
    default: run4evah

  - name: daqconfig_mongodb_root_password
    default: run4evah

targets:
  - name: pocket
    context: kind-pocketdune
    args:
      with_cilium: false
      with_kafka_kraft: true
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false
      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah

  - name: np04-services
    context: kubernetes-admin@np04-services
