---
discriminator: "dune-daq-{{ target.name }}"

args:
  - name: with_cilium
    default: true
  - name: with_cvmfs_csi
    default: true
  - name: with_dns_autoscaler
    default: true
  - name: with_dune_daq
    default: true
  - name: with_grafana
    default: true
  - name: grafana_admin_password # This should be customized as an argument for your needs
    default: run4evah
  - name: with_kepler
    default: true
  - name: with_kubernetes_dashboard
    default: true
  - name: with_nfs_storage
    default: true
  - name: with_node_feature_discovery
    default: true
  - name: with_node_problem_detector
    default: false
  - name: with_operators
    default: true
  - name: with_trivy
    default: false
  - name: with_kafka_kraft
    default: false
  - name: with_local_path_as_default_storageclass
    default: false

targets:
  - name: pocket
    context: kind-pocketdune
    args:
      with_cilium: false
      with_kafka_kraft: true
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

  - name: np04-services
    context: kubernetes-admin@np04-services
