---
discriminator: "dune-daq-{{ target.name }}"

args:
  - name: with_applications
    default: true
  - name: with_bootstrap
    default: true
  - name: with_baseline
    default: true
  - name: with_cilium
    default: true
  - name: with_cvmfs_csi
    default: true
  - name: with_cnpg_operator
    default: false
  - name: with_dns_autoscaler
    default: true
  - name: with_dune_daq
    default: true
  - name: with_grafana
    default: true
  - name: with_kepler
    default: true
  - name: with_kubernetes_dashboard
    default: true
  - name: with_minio_operator
    default: false
  - name: with_nfs_storage
    default: true
  - name: with_node_feature_discovery
    default: true
  - name: with_node_problem_detector
    default: false
  - name: with_strimzi_kafka_operator
    default: true
  - name: with_tinyproxy
    default: true
  - name: with_trivy
    default: false

  ### Feature flags for included manifests
  - name: with_kafka_kraft # strimzi doesn't support topicOperator with KRAFT yet
    default: false
  - name: with_kafka_ui
    default: true
  - name: with_local_path_as_default_storageclass
    default: false
  - name: with_mongo_express
    default: true

  ### Feature flags for application targets
  - name: with_dune_connectionservice
    default: true
  - name: with_dune_daqconfig
    default: true
  - name: with_dune_dqm
    default: true
  - name: with_dune_ers
    default: true
  - name: with_dune_kafka
    default: true
  - name: with_dune_opmon
    default: true
  - name: with_dune_runcounter
    default: true

  ### This should be customized as an argument for your needs
  ### Since `pocket` mode is for local development of services
  ### on node local ephemeral non-exposed containers, default passwords
  ### are acceptable.
  ###
  ### For real deployments you must set these to the correct values
  ###
  ### see: kluctl --args-from-file=filename
  - name: grafana_admin_password
  - name: daqconfig_mongodb_daqconfig_password
  - name: daqconfig_mongodb_root_password
  - name: dqm_backend_admin_password
  - name: ers_postgresql_password
  - name: opmon_influxdb_user_influxdb_password
  - name: opmon_telegraf_user_influxdb_password
  - name: opmon_influxdb_admin_password
  - name: runcounter_postgresql_password

targets:
  - name: pocket
    context: kind-pocketdune
    args:
      with_cilium: false
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah
      daqconfig_mongodb_daqconfig_password: run4evah
      dqm_backend_admin_password: admin
      ers_postgresql_password: run4evah
      opmon_influxdb_user_influxdb_password: dunedaq
      opmon_telegraf_user_influxdb_password: run4evah
      opmon_influxdb_admin_password: run4evah
      runcounter_postgresql_password: run4evah

  - name: pocket-connectionservice
    discriminator: "dune-daq-pocket"
    args:
      with_cilium: false
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

      with_dune_connectionservice: true
      with_dune_daqconfig: false
      with_dune_dqm: false
      with_dune_ers: false
      with_dune_kafka: false
      with_dune_opmon: false
      with_dune_runcounter: false

      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah
      daqconfig_mongodb_daqconfig_password: run4evah
      dqm_backend_admin_password: admin
      ers_postgresql_password: run4evah
      opmon_influxdb_user_influxdb_password: dunedaq
      opmon_telegraf_user_influxdb_password: run4evah
      opmon_influxdb_admin_password: run4evah
      runcounter_postgresql_password: run4evah

  - name: pocket-daqconfig
    discriminator: "dune-daq-pocket"
    args:
      with_cilium: false
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

      with_dune_connectionservice: false
      with_dune_daqconfig: true
      with_dune_dqm: false
      with_dune_ers: false
      with_dune_kafka: false
      with_dune_opmon: false
      with_dune_runcounter: false

      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah
      daqconfig_mongodb_daqconfig_password: run4evah
      dqm_backend_admin_password: admin
      ers_postgresql_password: run4evah
      opmon_influxdb_user_influxdb_password: dunedaq
      opmon_telegraf_user_influxdb_password: run4evah
      opmon_influxdb_admin_password: run4evah
      runcounter_postgresql_password: run4evah


  - name: pocket-dqm
    discriminator: "dune-daq-pocket"
    args:
      with_cilium: false
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

      with_dune_connectionservice: false
      with_dune_daqconfig: false
      with_dune_dqm: true
      with_dune_ers: false
      with_dune_kafka: true
      with_dune_opmon: false
      with_dune_runcounter: false

      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah
      daqconfig_mongodb_daqconfig_password: run4evah
      dqm_backend_admin_password: admin
      ers_postgresql_password: run4evah
      opmon_influxdb_user_influxdb_password: dunedaq
      opmon_telegraf_user_influxdb_password: run4evah
      opmon_influxdb_admin_password: run4evah
      runcounter_postgresql_password: run4evah

  - name: pocket-ers
    discriminator: "dune-daq-pocket"
    args:
      with_cilium: false
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

      with_dune_connectionservice: false
      with_dune_daqconfig: false
      with_dune_dqm: false
      with_dune_ers: true
      with_dune_kafka: true
      with_dune_opmon: false
      with_dune_runcounter: false

      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah
      daqconfig_mongodb_daqconfig_password: run4evah
      dqm_backend_admin_password: admin
      ers_postgresql_password: run4evah
      opmon_influxdb_user_influxdb_password: dunedaq
      opmon_telegraf_user_influxdb_password: run4evah
      opmon_influxdb_admin_password: run4evah
      runcounter_postgresql_password: run4evah

  - name: pocket-opmon
    discriminator: "dune-daq-pocket"
    args:
      with_cilium: false
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

      with_dune_connectionservice: false
      with_dune_daqconfig: false
      with_dune_dqm: false
      with_dune_ers: false
      with_dune_kafka: true
      with_dune_opmon: true
      with_dune_runcounter: false

      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah
      daqconfig_mongodb_daqconfig_password: run4evah
      dqm_backend_admin_password: admin
      ers_postgresql_password: run4evah
      opmon_influxdb_user_influxdb_password: dunedaq
      opmon_telegraf_user_influxdb_password: run4evah
      opmon_influxdb_admin_password: run4evah
      runcounter_postgresql_password: run4evah

  - name: pocket-runcounter
    discriminator: "dune-daq-pocket"
    args:
      with_cilium: false
      with_local_path_as_default_storageclass: true
      with_nfs_storage: false

      with_dune_connectionservice: false
      with_dune_daqconfig: false
      with_dune_dqm: false
      with_dune_ers: false
      with_dune_kafka: false
      with_dune_opmon: false
      with_dune_runcounter: true

      grafana_admin_password: run4evah
      daqconfig_mongodb_root_password: run4evah
      daqconfig_mongodb_daqconfig_password: run4evah
      dqm_backend_admin_password: admin
      ers_postgresql_password: run4evah
      opmon_influxdb_user_influxdb_password: dunedaq
      opmon_telegraf_user_influxdb_password: run4evah
      opmon_influxdb_admin_password: run4evah
      runcounter_postgresql_password: run4evah


  - name: np04-services
    context: kubernetes-admin@np04-services
    args:
      with_kafka_ui: false
      with_mongo_express: false
