---
discriminator: "dune-daq-{{ target.name }}"

args:
  - name: inside_kind
    default: false

  - name: with_local_path_as_default_storageclass
    default: true

  - name: with_baseline
    default: true

  - name: with_applications
    default: true

  - name: with_dune_applications
    default: true

  - name: with_dune_readout
    default: false

  - name: with_node_ports
    default: true

  - name: user_passwords
    default: run4evah

  - name: oracle_password
    default: run4evah # only matters for np04-services

  - name: elisa_password
    default: run4evah # only matters for np04-services

targets:
  - name: pocket
    args:
      inside_kind: true

  - name: pocket-bootstrap
    args:
      inside_kind: true
      with_applications: false
      with_baseline: false
      with_dune_applications: false

  - name: pocket-baseline
    args:
      inside_kind: true
      with_applications: false
      with_dune_applications: false

  - name: pocket-applications
    args:
      inside_kind: true
      with_dune_applications: false

  - name: iceberg-services
    discriminator: "iceberg-daq-pocket"
    args:
      inside_kind: true
      user_passwords: NULL

  - name: np04-services
    context: kubernetes-admin@np04-services
    args:
      user_passwords: NULL
      elisa_password: NULL
      oracle_password: NULL

  - name: np04-daq
    context: kubernetes-admin@np04-daq
    args:
      user_passwords: NULL
      with_dune_readout: true
      with_dune_applications: false
