---
deployments:
  - include: baseline
    skipDeleteIfTags: true

{% if not args.with_cni_only %}
  - barrier: true
    message: Ensure baseline is loaded

  - include: operators
  - barrier: true

  - include: applications

{% if args.with_dune_daq %}
  - include: dune_daq
    tags:
      - dune
      - daq
{% endif %}
{% endif %}

vars:
  - file: variables/monitoring.yaml

  - file: variables/alertmanager_labels.yaml
  - file: variables/prometheus_labels.yaml
  - file: variables/grafana_labels.yaml
  - file: variables/grafana_default_dashboard.yaml

  - file: variables/kafka.yaml # figure out how to store these better
  - file: variables/minio.yaml # figure out how to store these better
  - file: variables/postgresql.yaml # figure out how to store these better

  - file: variables/targets/{{ target.name }}.yaml

ignoreForDiff:
  - kind: PrometheusRule
    fieldPath: .metadata.annotations["prometheus-operator-validated"]
