---
deployments:
  - path: .submodules
    onlyRender: true

  - include: bootstrap
    skipDeleteIfTags: true

  - barrier: true
    message: Ensure cluster has bootstraps

{% if args.with_baseline %}
  - include: baseline
    skipDeleteIfTags: true

  - barrier: true
    message: Ensure baseline is loaded

{% if args.with_applications %}
  - include: applications
    tags:
      - services

  - barrier: true
    message: Ensure applications are loaded

  - include: dune_applications
    tags:
      - dune

{% if args.with_node_ports %}
  - include: node-ports
    tags:
      - services
      - nodeport
{% endif %}
{% endif %}
{% endif %}

vars:
  - values:
      inside_kind: {{ args.inside_kind }}

  - file: variables/check_required.yaml
  - file: variables/defaults/alertmanager_labels.yaml
  - file: variables/defaults/certmanager_settings.yaml
  - file: variables/defaults/cilium.yaml
  - file: variables/defaults/cluster_info.yaml
  - file: variables/defaults/cvmfs_csi.yaml
  - file: variables/defaults/development_instance.yaml
  - file: variables/defaults/external_secrets_info.yaml
  - file: variables/defaults/grafana_extra_settings.yaml
  - file: variables/defaults/grafana_labels.yaml
  - file: variables/defaults/kubernetes_labels.yaml
  - file: variables/defaults/monitoring.yaml
  - file: variables/defaults/node_local_path_base.yaml
  - file: variables/defaults/prometheus_labels.yaml
  - file: variables/defaults/prometheus_scrape_configs.yaml
  - file: variables/defaults/smtp_server.yaml
  - file: variables/defaults/user_password.yaml

{% if 'pocket' in target.name %}
  - file: variables/targets/pocket.yaml
{% else %}
  - file: variables/targets/{{ target.name }}.yaml
{% endif %}

ignoreForDiff:
  - kind: PrometheusRule
    fieldPath: .metadata.annotations["prometheus-operator-validated"]
{% if 'pocket' in target.name %}
  - fieldPath: .metadata.labels["kluctl.io/discriminator"]
{% endif %}
