---
deployments:
  - path: .submodules
    onlyRender: true

  - include: bootstrap
    skipDeleteIfTags: true

  - barrier: true
    message: Ensure cluster has bootstraps

  - include: baseline
    skipDeleteIfTags: true

  - barrier: true
    message: Ensure baseline is loaded

  - include: operators

  - barrier: true
    message: Make sure operators have settled

  - include: applications

  - include: dune_daq_services
    tags:
      - dune
      - daq
      - services

  - include: node-ports
    tags:
      - dune
      - daq
      - services
      - ports

vars:
{% if args.in_pocket %}
  - file: variables/targets/pocket-defaults.yaml
{% endif %}
  - file: variables/targets/{{ target.name }}.yaml
  - file: variables/defaults.yaml
    noOverride: true

  - file: variables/monitoring.yaml
  - file: variables/certmanager_bundle.yaml

  - file: variables/alertmanager_labels.yaml
  - file: variables/prometheus_labels.yaml
  - file: variables/grafana_labels.yaml
  - file: variables/grafana_default_dashboard.yaml
  - file: variables/local_path_provisioner.yaml # for StorageClass name

  - file: variables/kafka.yaml # figure out how to store these better
  - file: variables/minio.yaml # figure out how to store these better
  - file: variables/postgresql.yaml # figure out how to store these better

ignoreForDiff:
  - kind: PrometheusRule
    fieldPath: .metadata.annotations["prometheus-operator-validated"]
