---
deployments:
  - path: .submodules
    onlyRender: true

{% if args.with_bootstrap %}
  - include: bootstrap
    skipDeleteIfTags: true

  - barrier: true
    message: Ensure cluster has bootstraps
{% endif %}

{% if args.with_baseline %}
  - include: baseline
    skipDeleteIfTags: true

  - barrier: true
    message: Ensure baseline is loaded
{% endif %}

{% if args.with_applications %}
  - include: operators
  - barrier: true

  - include: applications
{% endif %}

{% if args.with_dune_daq_services %}
  - include: dune_daq_services
    tags:
      - dune
      - daq
      - services
{% endif %}

vars:
  - file: variables/monitoring.yaml
  - file: variables/certmanager_bundle.yaml

  - file: variables/alertmanager_labels.yaml
  - file: variables/prometheus_labels.yaml
  - file: variables/grafana_labels.yaml
  - file: variables/grafana_default_dashboard.yaml
  - file: variables/local_path_provisioner.yaml # for StorageClass name

  - file: variables/kafka.yaml # figure out how to store these better
  - file: variables/minio.yaml # figure out how to store these better
  - file: variables/postgresql.yaml # figure out how to store these better

  - file: variables/targets/{{ target.name }}.yaml

ignoreForDiff:
  - kind: PrometheusRule
    fieldPath: .metadata.annotations["prometheus-operator-validated"]
