---
auth:
  username: "{{ ERS_postgresql.database_username }}"
  password: "{{ ERS_postgresql.database_password }}"
  database: "{{ ERS_postgresql.database_name }}"
  postgresPassword: "{{ ERS_postgresql.database_password }}"

architecture: standalone

serviceBindings:
  enabled: true

primary:
  initdb:
    args: '--data-checksums --locale=en_US.UTF-8 --set huge_pages=off'

  extendedConfiguration: |-
    log_destination = stderr
    log_timezone = UTC
    timezone = UTC
    huge_pages = off

  persistence: # this is guess work
    enabled: true
    size: 4Gi
    storageClass: {{ local_path_provisioner.storage_class_name }}

  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: {{ kubernetes_worker_label }}
           operator: Exists

shmVolume:
  enabled: true

resources: # this is guess work
  requests:
    cpu: 100m
    memory: 64Mi

affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: {{ kubernetes_worker_label }}
         operator: Exists

{% if args.with_backups %}
backup:
  enabled: true
  successfulJobsHistoryLimit: 1
{% endif %}

metrics:
  enabled: true
  resources: # this is guess work
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 500m
      memory: 1Gi
  serviceMonitor:
    enabled: true
    labels:
      jobLabel: postgresql-ers
      "{{ prometheus_servicemonitor_label_name }}": "{{ prometheus_servicemonitor_labels.postgresql }}"
    jobLabel: jobLabel
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    labels:
      "{{ prometheus_rule_label_name }}": "{{ prometheus_rule_labels.postgresql }}"
