---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sriovdp-config.yaml
  - sriovdp-daemonset.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: kube-sriov-device-plugin-ppc64le
    patch: |-
      $patch: delete
      kind: Kustomization
      metadata:
        name: DOES NOT MATTER
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: kube-sriov-device-plugin-arm64
    patch: |-
      $patch: delete
      kind: Kustomization
      metadata:
        name: DOES NOT MATTER
