---
deployments:
  - path: namespace
    alwaysDeploy: true

  - path: cnpg
    waitReadiness: true

  - barrier: true
    message: cnpg needs to settle (about 2m)

vars:
  - file: variables/cnpg.yaml
