---
deployments:
  - path: namespace
    alwaysDeploy: true

  - barrier: true
    message: We need a namespace to deploy into
    waitReadinessObjects:
      - kind: Namespace

  - path: cnpg
    waitReadiness: true

  - barrier: true
    message: cnpg needs to settle (about 2m)

vars:
  - file: variables/cnpg.yaml
