---
prometheus_operator_namespace: kube-prometheus
prometheis: # this is the plural of prometheus
  main:
    namespace: {{ monitoring.namespace }}
    name: main
    serviceName: prometheus
{% if 'pocket' in target.name %}
    grafanaDatasourceName: prometheus-pocket
{% else %}
    grafanaDatasourceName: prometheus-{{ target.name }}
{% endif %}
    url: http://prometheus.{{ monitoring.namespace }}.svc.cluster.local
    port: 9090
    portName: web
    replicas: 1
    alertmanagers:
      - namespace: {{ alertmanagers.main.namespace }}
        name: {{ alertmanagers.main.serviceName }}
        port: {{ alertmanagers.main.portName }}

    # try to schedule on same node as alertmanager
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: {{ kubernetes_labels.node_worker }}
              operator: Exists
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 30
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: alertmanager
                  operator: Exists
              topologyKey: kubernetes.io/hostname

    # these limits should probably be tuned a bit
    # but the wal log is memory hungry
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
    logLevel: debug
    scrapeInterval: 45s
    scrapeTimeout: 35s
    retention: 95d
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
{% if 'pocket' in target.name %}
            requests:
              storage: 75Gi
{% else %}
            requests:
              storage: 185Gi
{% endif %}
{% if 'pocket' in target.name %}
    retentionSize: 60GB
{% else %}
    retentionSize: 170GB
{% endif %}

    # these selectors should probably be set to rational filters
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    probeNamespaceSelector: {}
    probeSelector: {}
    ruleNamespaceSelector: {}
    ruleSelector: {}
    scrapeConfigNamespaceSelector: {}
    scrapeConfigSelector: {}
