---
architecture: standalone

directoryPerDB: true

useStatefulSet: true

auth: {{ DUNE_daqconfig.mongodb_authentication | tojson }}

serviceBindings:
  enabled: true

persistence:
  enabled: true
  storageClass: {{ local_path_provisioner.storage_class_name }}

{% if args.with_backups %}
backup:
  enabled: true
  successfulJobsHistoryLimit: 1
{% endif %}

metrics: # TODO https://github.com/percona/grafana-dashboards/tree/main/dashboards/MongoDB
  enabled: true
  compatibleMode: false # skip old metrics
  username: metrics
  # password:
  collector:
    all: true
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 512Mi
  serviceMonitor:
    enabled: true
    labels:
      "{{ prometheus_servicemonitor_label_name }}": "{{ prometheus_servicemonitor_labels.mongodb }}"
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    additionalLabels:
      "{{ prometheus_rule_label_name }}": "{{ prometheus_rule_labels.mongodb }}"
