---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
  namespace: {{ DUNE_daqconfig.namespace }}
  labels:
    app.kubernetes.io/app: mongodb-express
    app.kubernetes.io/component: mongodb-express
    app.kubernetes.io/instance: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: mongodb-express
      app.kubernetes.io/component: mongodb-express
      app.kubernetes.io/instance: mongodb-express
  template:
    metadata:
      labels:
        app.kubernetes.io/app: mongodb-express
        app.kubernetes.io/component: mongodb-express
        app.kubernetes.io/instance: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          # https://github.com/mongo-express/mongo-express/issues/1170
          image: docker.io/library/mongo-express
          ports:
            - containerPort: 8081
              name: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: daqconfig-mongodb-svcbind-root
                  key: uri
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true" # should be false once we fix credentials
            - name: ME_CONFIG_OPTIONS_NO_DELETE
              value: "true"
            - name: ME_CONFIG_OPTIONS_READONLY
              value: "true"
          securityContext:
            runAsUser: 10000
            runAsGroup: 10000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 10000
