---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ DUNE_opmon.namespace }}
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels: # influxdb v1 chart isn't restricted compatible
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
