---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-datasource-{{ dune_online_opmon.database.postgresql_timescaledb.deployment }}
  namespace: {{ dune_online_opmon.namespace }}
spec:
  secretStoreRef: {{ external_secrets.kubernetes_secretStore | tojson }}
  target:
    template:
      metadata:
        labels:
          {{ grafana_datasource_label_name }}: {{ grafana_datasource_label_value }}
      data:
        datasource_{{ dune_online_opmon.database.postgresql_timescaledb.deployment }}_postgres.yaml: |-
          apiVersion: 1
          datasources:
          - name: OpmonTimescaleDB
            uid: OpmonTimescaleDB
            type: postgres
            url: "{{ dune_online_opmon.database.postgresql_timescaledb.deployment }}-r.{{ dune_online_opmon.namespace }}.svc:5432" # 'r' targets any instance, 'ro' targets read-only instances ONLY
            user: readonly
            secureJsonData:
{% raw %}
              password: "{{ .password }}"
{% endraw %}
            jsonData:
              database: {{ dune_online_opmon.database.postgresql_timescaledb.database }}
              sslmode: require
              tlsSkipVerify: true # my heart breaks
              maxIdleConns: 2 # this is guess work
              postgresVersion: 1500 # this should be smarter somehow....
              timescaledb: true
  data:
    - secretKey: password
      remoteRef: {{ external_secrets.static_password | tojson }}
