---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ dune_online_opmon.database.postgresql_timescaledb.deployment }}-postgresql-exporter-password
  namespace: {{ dune_online_opmon.namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    creationPolicy: Orphan
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgresql_exporter
{% raw %}
        password: "{{ .uuid }}"
{% endraw %}
        database: {{ dune_online_opmon.database.postgresql_timescaledb.database }}
        host: {{ dune_online_opmon.database.postgresql_timescaledb.deployment }}-r.{{ dune_online_opmon.namespace }}.svc
        port: '5432'
        uri: "postgresql://postgresql_exporter:{% raw %}{{ .uuid }}{% endraw %}@{{ dune_online_opmon.database.postgresql_timescaledb.deployment }}-r.{{ dune_online_opmon.namespace }}.svc:5432/{{ dune_online_opmon.database.postgresql_timescaledb.database }}"
        pyuri: "postgresql+psycopg://postgresql_exporter:{% raw %}{{ .uuid }}{% endraw %}@{{ dune_online_opmon.database.postgresql_timescaledb.deployment }}-r.{{ dune_online_opmon.namespace }}.svc:5432/{{ dune_online_opmon.database.postgresql_timescaledb.database }}"
  dataFrom:
    - sourceRef:
        generatorRef: {{ external_secrets.uuid | tojson }}
