---
# is this actually needed?
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-datasource-{{ dune_online_runservices.database.postgresql.deployment }}
  namespace: {{ dune_online_runservices.namespace }}
spec:
  secretStoreRef: {{ external_secrets.kubernetes_secretStore | tojson }}
  target:
    template:
      metadata:
        labels:
          {{ grafana_datasource_label_name }}: {{ grafana_datasource_label_value }}
      data:
        datasource_{{ dune_online_runservices.database.postgresql.deployment }}_postgres.yaml: |-
          apiVersion: 1
          datasources:
          - name: RunReg
            uid: RunReg
            type: postgres
            url: "{{ dune_online_runservices.database.postgresql.deployment }}-r.{{ dune_online_runservices.namespace }}.svc:5432" # 'r' targets any instance, 'ro' targets read-only instances ONLY
            user: readonly
            secureJsonData:
{% raw %}
              password: "{{ .password }}"
{% endraw %}
            jsonData:
              database: {{ dune_online_runservices.database.postgresql.database }}
              sslmode: require
              tlsSkipVerify: true # my heart breaks
              maxIdleConns: 2 # this is guess work
              postgresVersion: 1500 # this should be smarter somehow....
  data:
    - secretKey: password
      remoteRef: {{ external_secrets.static_password | tojson }}
