---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql_exporter-password-generated-secret.yaml
  - readonly-password-generated-secret.yaml
  - runservices-password-generated-secret.yaml
