---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ dune_online_runservices.database.postgresql.deployment }}-postgresql-exporter-password
  namespace: {{ dune_online_runservices.namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    creationPolicy: Orphan
    template:
      type: kubernetes.io/basic-auth
      data:
        username: postgresql_exporter
{% raw %}
        password: "{{ .uuid }}"
{% endraw %}
        database: {{ dune_online_runservices.database.postgresql.database }}
        host: {{ dune_online_runservices.database.postgresql.deployment }}-r.{{ dune_online_runservices.namespace }}.svc
        port: '5432'
        uri: "postgresql://postgresql_exporter:{% raw %}{{ .uuid }}{% endraw %}@{{ dune_online_runservices.database.postgresql.deployment }}-r.{{ dune_online_runservices.namespace }}.svc:5432/{{ dune_online_runservices.database.postgresql.database }}"
  dataFrom:
    - sourceRef:
        generatorRef: {{ external_secrets.uuid | tojson }}
