---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ dune_online_runservices.database.postgresql.deployment }}-readonly-password
  namespace: {{ dune_online_runservices.namespace }}
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef: {{ external_secrets.kubernetes_secretStore | tojson }}
  target:
    creationPolicy: Orphan
    template:
      type: kubernetes.io/basic-auth
      data:
        username: readonly
{% raw %}
        password: "{{ .decoded }}"
{% endraw %}
        database: {{ dune_online_runservices.database.postgresql.database }}
        host: {{ dune_online_runservices.database.postgresql.deployment }}-r.{{ dune_online_runservices.namespace }}.svc
        port: '5432'
        uri: "postgresql://readonly:{% raw %}{{ .decoded }}{% endraw %}@{{ dune_online_runservices.database.postgresql.deployment }}-r.{{ dune_online_runservices.namespace }}.svc:5432/{{ dune_online_runservices.database.postgresql.database }}"
  data:
    - secretKey: decoded
      remoteRef: {{ external_secrets.static_password | tojson }}
