---
deployments:
  - path: grafana-dashboards-kubernetes-dotdc
    tags:
      - grafana-dashboards
      - grafana-dashboards-kubernetes

  - path: grafana-dashboards-kubernetes-kube-prometheus
    tags:
      - grafana-dashboards
      - grafana-dashboards-kubernetes

  - barrier: true
    message: Ensure kubernetes dashboards are loaded

  - path: grafana-server-main
  - path: grafana-server-devel
  - path: grafana-server-devel-other

vars:
  - file: variables/grafana.yaml
