---
deployments:
  - path: grafana-dashboards-kubernetes-dotdc
    tags:
      - grafana-dashboards
      - grafana-dashboards-kubernetes

  - path: grafana-dashboards-rfmoz
    tags:
      - grafana-dashboards
      - grafana-dashboards-kubernetes

  - path: grafana-password

  - barrier: true
    message: Ensure kubernetes grafana dashboards and passwords are loaded

  - path: grafana-server-main

{% if development_instance %}
  - path: grafana-server-devel
{% endif %}

vars:
  - file: variables/grafana.yaml
