---
architecture: standalone

directoryPerDB: true

useStatefulSet: true

auth:
  rootUser: {{ DUNE_daqconfig.mongodb_root_user }}
  rootPassword: {{ DUNE_daqconfig.mongodb_root_password }}

serviceBindings:
  enabled: true

persistence:
  enabled: true
  # storageClass: when unset uses default class

metrics: # TODO https://github.com/percona/grafana-dashboards/tree/main/dashboards/MongoDB
  enabled: true
  compatibleMode: false # skip old metrics
  username: metrics
  # password:
  collector:
    all: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  serviceMonitor:
    enabled: true
    labels:
      "{{ prometheus_servicemonitor_label_name }}": "{{ prometheus_servicemonitor_labels.dune }}"
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    additionalLabels:
      "{{ prometheus_rule_label_name }}": "{{ prometheus_rule_labels.dune }}"
