---
deployments:
{% if with_applications %}
{% if with_tinyproxy %}
  - path: microsocks
{% endif %}

{% if with_kepler %}
{% if not inside_kind %}
  - include: kepler
    tags:
      - monitoring
      - metrics
{% endif %}
{% endif %}

{% if with_node_feature_discovery %}
  - include: node-feature-discovery
{% if with_pcm %}
  - path: intel-pcm
{% endif %}
{% endif %}

{% if with_kubernetes_dashboard %}
  - include: kubernetes-dashboard
{% endif %}

{% if with_nfs_storage %}
  - include: nfs-storage
    tags:
      - nfs
      - storage
{% endif %}

{% if with_cvmfs_csi %}
  - include: cvmfs-csi
    tags:
      - cvmfs
      - storage
{% endif %}

{% if with_sriov %}
  - path: sriov-network-device-plugin
    tags:
      - sriov
      - dpdk
{% endif %}

{% if with_dune_felix_plugin %}
  - include: felix-plugin
{% endif %}

{% if with_grafana %}
  - barrier: true
    message: Let grafana dashboard config maps finish loading

  - include: grafana
    tags:
      - monitoring
      - metrics
{% endif %}
{% endif %}

  - barrier: true
    message: Finish loading applications
