---
deployments:
  - include: cvmfs-csi
    tags:
      - csi
      - cvmfs
      - storage

  - include: kubernetes-dashboard-application

  - include: node-feature-discovery

  - path: microsocks

{% if hardware_access %}
  - path: sriov-network-device-plugin
    tags:
      - sriov
      - dpdk
  - path: intel-pcm
    tags:
      - pcm
      - monitoring
      - metrics
{% endif %}

  - barrier: true
    message: Let grafana dashboard config maps finish loading

  - include: grafana
    tags:
      - monitoring
      - metrics

  - barrier: true
    message: Finish loading applications
