---
deployments:
{% if args.with_dune_readout %}
  - include: cvmfs-csi
    tags:
      - csi
      - cvmfs
      - storage
{% endif %}

  - include: headlamp

  - path: microsocks

{% if hardware_access %}
  - include: kepler
    tags:
      - monitoring
      - metrics
      - power

{% if args.with_dune_readout %}
  - path: sriov-network-device-plugin
    tags:
      - sriov
      - dpdk

  - path: intel-pcm
    tags:
      - monitoring
      - metrics
      - pcm
{% endif %}
{% endif %}

  - barrier: true
    message: Let grafana dashboard config maps finish loading

  - include: grafana
    tags:
      - monitoring
      - metrics

  - barrier: true
    message: Finish loading applications
