---
deployments:
{% if args.with_trivy %}
  - include: trivy
{% endif %}

{% if args.with_tinyproxy %}
  - path: tinyproxy
{% endif %}

{% if args.with_kepler %}
  - include: kepler
    tags:
      - monitoring
      - metrics
{% endif %}

{% if args.with_node_feature_discovery %}
  - include: node-feature-discovery
{% endif %}

{% if args.with_multus_cni %}
  - include: multus-cni
{% endif %}

{% if args.with_node_problem_detector %}
  - include: node-problem-detector
    tags:
      - monitoring
      - metrics
{% endif %}

{% if args.with_kubernetes_dashboard %}
  - include: kubernetes-dashboard
{% endif %}

{% if args.with_nfs_storage %}
  - include: nfs-storage
    tags:
      - nfs
      - storage
{% endif %}

{% if args.with_cvmfs_csi %}
  - include: cvmfs-csi
    tags:
      - cvmfs
      - storage
{% endif %}

{% if args.with_grafana %}
  - barrier: true
    message: "Let grafana dashboard config maps finish loading"

  - include: grafana
    tags:
      - monitoring
      - metrics
{% endif %}
