---
deployments:
  - path: namespace

  - barrier: true

  - path: metrics

  - path: kafka-server

{% if with_kafka_ui %}
  - path: kafka-ui
{% endif %}

vars:
- systemEnvVars:
    kafka_hostname: HOSTNAME
