{% for thishardware in dunedaq.elisa_logbook_hardware_types %}
---
apiVersion: v1
kind: Secret
metadata:
  name: elisa-logbook-secret-{{ thishardware }}
  namespace: {{ elisa_logbook_namespace }}
stringData:
  username: {{ args.elisa_logbook_username }}
  password: {{ args.elisa_logbook_password }}
  hardware: {{ thishardware }}
{% endfor %}
