---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ DUNE_ers.namespace }}

resources:
  - ers-kafka-dbwriter-settings.yml
  - ers-kafka-dbwriter.yml

patchesJSON6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: {{ dunedaq.unified-microservices.image }}:{{ dunedaq.unified-microservices.tag }}
