---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ DUNE_ers.namespace }}

resources:
  - ersdbwriter.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: {{ dunedaq.unified_microservices.image }}:{{ dunedaq.unified_microservices.tag }}
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: {{ dunedaq.kafka.bootstrap_brokers[0] }}
