---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-view: "true"
  name: headlamp-read-only-cluster-resources
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - volumeattachments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headlamp-read-only-role
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-view: "true"
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-cluster-view: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-read-only-role
  namespace: {{ headlamp.namespace }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-read-only-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headlamp-read-only-role
subjects:
  - kind: ServiceAccount
    name: headlamp-read-only-role
    namespace: {{ headlamp.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-read-only-token
  namespace: {{ headlamp.namespace }}
  annotations:
    kubernetes.io/service-account.name: headlamp-read-only-role
type: kubernetes.io/service-account-token
