---
config:
  secret: true

monitoring:
  podMonitorEnabled: true
  podMonitorAdditionalLabels:
    {{ prometheus_podmonitor_label_name }}: {{ prometheus_podmonitor_labels.postgresql }}
  grafanaDashboard:
    create: true
    labels:
      {{ grafana_dashboard_label_name }}: {{ grafana_dashboard_label_value }}
    annotations:
      {{ grafana_dashboard_folder_annotation }}: Postgresql

rbac:
  aggregateClusterRoles: true

resources:
  limits:
    memory: 384Mi
    cpu: 1000m
  requests:
    memory: 384Mi
    cpu: 200m

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ kubernetes_labels.node_worker }}
              operator: Exists

podDisruptionBudget:
  enabled: true
  minAvailable: 0
  unhealthyPodEvictionPolicy: AlwaysAllow
