---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ prometheus_control_plane_service_account_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: {{ prometheus_control_plane_service_account_name }}
  namespace: {{ prometheus_operator_namespace }}
