---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ prometheus_control_plane_token_secret_name }}
  namespace: {{ prometheus_operator_namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ prometheus_control_plane_service_account_name }}
