---
tplVersion: 2

config:
  inputs:
  - kafka_consumer:
      brokers: {{ dunedaq.kafka.bootstrap_brokers | tojson }}
      topics: {{ OPMON_telegraf.kafka_topics | tojson }}
      version: "{{ dunedaq.kafka.version }}"
      client_id: 'opmon-telegraf'
      data_format: json_v2
      consumer_group: 'opmon-telegraf'
      json_v2:
        measurement_name_path: measurement
        timestamp_path: time
        timestamp_format: '2023-07-13T14:59:51Z'
        object:
          tags:
            - tags
          fields:
            key: fields

  outputs:
  - prometheus_client: # for prometheus
      listen: ":{{ OPMON_telegraf.prometheus_port }}"
  - influxdb: # influxdb_v1, need to switch to v2
      urls: 
        - http://opmon-influxdb.{{ DUNE_opmon.namespace }}.svc:8086
      database: {{ OPMON_telegraf.influxdb_database }}
      username: {{ OPMON_telegraf.influxdb_username }}
      password: "{{ OPMON_telegraf.influxdb_password }}"

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions: # try to schedule near Kafka
          - key: "strimzi.io/cluster"
            operator: In
            values:
            - "{{ dunedaq.kafka.name }}"
        namespaceSelector:
          matchLabels:
            name: {{ dunedaq.kafka.namespace }}
        topologyKey: kubernetes.io/hostname
    - weight: 90
      podAffinityTerm:
        labelSelector:
          matchExpressions: # try to schedule near Influxdb
          - key: "app.kubernetes.io/instance"
            operator: In
            values:
            - "opmon-influxdb"
        namespaceSelector:
          matchLabels:
            name: {{ DUNE_opmon.namespace }}
        topologyKey: kubernetes.io/hostname

resources:
  requests:
    cpu: 50m
    memory: 32Mi

nodeSelector:
  kubernetes.io/os: linux
