---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{ prometheus_podmonitor_label_name }}: {{ prometheus_podmonitor_labels.dune }}
  name: telegraf
  namespace: {{ telegraf.namespace }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
      scheme: http
      scrapeTimeout: 5s
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - {{ telegraf.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: telegraf
      app.kubernetes.io/name: telegraf
  endpoints:
    - port: prometheus-client
