---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{ prometheus_podmonitor_label_name }}: {{ prometheus_podmonitor_labels.dune }}
  name: telegraf
  namespace: {{ telegraf.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: telegraf
  podMetricsEndpoints:
    - port: {{ telegraf.prometheus_port }}
