---
deployments:
  - path: namespace

  - barrier: true

  - path: kafka-topic
  - path: postgresql

  - barrier: true
    message: Let services all catch up

  - path: telegraf

vars:
  - file: variables/ers.yaml
  - file: variables/postgresql.yaml
  - file: variables/telegraf.yaml
