---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ cvmfs_csi.namespace }}"
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels: # needs hostPID access
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
