---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ dune_online_runservices.namespace }}

resources:
  - runnumber-rest-deployment.yaml

patches:
  - target:
      kind: Namespace
    patch: |-
      $patch: delete
      kind: Kustomization
      metadata:
        name: DOES NOT MATTER

  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: {{ dune_online.unified_microservices.image }}:{{ dune_online.unified_microservices.tag }}
      - op: replace
        path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0/key
        value: {{ kubernetes_labels.node_worker }}

  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
        value: {{ dune_online_runservices.database.postgresql.deployment }}-{{ dune_online_runservices.database.postgresql.owner }}-password
