---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ certmanager_ca_bundle_name }}
spec:
  sources:
  - useDefaultCAs: true
  target:
    configMap:
      key: {{ certmanager_ca_bundle_key }}
  namespaceSelector: {}
