apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-rendered.yaml
  - ca-bundle.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: trust-manager
    includeSelectors: true
