---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: python-tiny-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: python-tiny-proxy
    app.kubernetes.io/component: python-tiny-proxy
  name: python-tiny-proxy
  namespace: python-tiny-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: python-tiny-proxy
      app.kubernetes.io/component: python-tiny-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/app: python-tiny-proxy
        app.kubernetes.io/component: python-tiny-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ kubernetes_label.worker }}
                operator: Exists
      containers:
      - image: ghcr.io/dune-daq/python-tiny-proxy:latest
        imagePullPolicy: Always
        name: python-tiny-proxy
        ports:
        - containerPort: 1080
          name: socks5
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 8Mi
            cpu: 5m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          runAsUser: 10000
          runAsGroup: 10000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 10000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: python-tiny-proxy
    app.kubernetes.io/component: python-tiny-proxy
  name: python-tiny-proxy
  namespace: python-tiny-proxy
spec:
  ports:
  - name: socks5
    protocol: TCP
    port: 1080 # 1080 is the ICANN socks5 port
    targetPort: 1080
  selector:
    app.kubernetes.io/app: python-tiny-proxy
    app.kubernetes.io/component: python-tiny-proxy
  type: ClusterIP
