# 1. ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-view-secrets
  namespace: {{ external_secrets.namespace }}
---
# 2. Role for secrets in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
  namespace: {{ external_secrets.lookup_namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
# 3. RoleBinding for secrets access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-view-secrets
  namespace: {{ external_secrets.lookup_namespace }}
subjects:
  - kind: ServiceAccount
    name: external-secrets-view-secrets
    namespace: {{ external_secrets.namespace }}
roleRef:
  kind: Role
  name: view-secrets
  apiGroup: rbac.authorization.k8s.io
---
# 4. ClusterRole for viewing namespaces so we can list them
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-namespaces
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
# 5. ClusterRoleBinding to bind ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-view-namespaces
subjects:
  - kind: ServiceAccount
    name: external-secrets-view-secrets
    namespace: {{ external_secrets.namespace }}
roleRef:
  kind: ClusterRole
  name: view-namespaces
  apiGroup: rbac.authorization.k8s.io
