---
apiVersion: external-secrets.io/v1
kind: {{ external_secrets.kubernetes_secretStore.kind }}
metadata:
  name: {{ external_secrets.kubernetes_secretStore.name }}
  namespace: {{ external_secrets.namespace }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ external_secrets.lookup_namespace }}
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: default
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-view-secrets
          namespace: {{ external_secrets.namespace }}
