---
# Must be created in the same namespace as the secrets it generates
apiVersion: {{ external_secrets.uuid.apiVersion }}
kind: {{ external_secrets.uuid.kind }}
metadata:
  name: {{ external_secrets.uuid.name }}
  namespace: {{ external_secrets.lookup_namespace }}
spec: {}
