---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ grafana_datasource_label_name }}: {{ grafana_datasource_label_value }}
  name: grafana-datasource-{{ DUNE_runcounter.postgresql_database_name | lower }}
  namespace: {{ DUNE_ers.namespace }}
stringData:
  datasource_runcounter_postgresql_{{ DUNE_runcounter.postgresql_database_name | lower }}.yaml: |-
    apiVersion: 1
    datasources:
    - name: RunReg
      type: postgres 
      url: "{{ DUNE_runcounter.postgresql_release_name }}.{{DUNE_runcounter.namespace }}.svc:5432"
      database: {{ DUNE_runcounter.postgresql_database_name }}
      jsonData:
        sslmode: "disable" # my heart breaks
        tlsSkipVerify: true # my heart breaks
        postgresVersion: 1500
        maxIdleConns: 2
      user: {{ DUNE_runcounter.postgresql_database_username }}
      secureJsonData:
        password: {{ DUNE_runcounter.postgresql_database_password }}
