---
auth:
  username: "{{ DUNE_runcounter.postgresql_database_username }}"
  password: "{{ DUNE_runcounter.postgresql_database_password }}"
  database: "{{ DUNE_runcounter.postgresql_database_name }}"

architecture: standalone

serviceBindings:
  enabled: true

primary:
  initdb:
    args: '--data-checksums --locale=en_US.UTF-8'
    scriptsConfigMap: runnum-table-sql

  extendedConfiguration: |-
    log_destination = stderr
    log_timezone = UTC
    timezone = UTC

  persistence:
    enabled: true
    size: 4Gi # this is guesswork
    storageClass: {{ local_path_provisioner.storage_class_name }}

resources: # this is guesswork
  requests:
    cpu: 10m
    memory: 64Mi

metrics:
  enabled: true
  resources: # this is guesswork
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 300m
      memory: 512Mi
  serviceMonitor:
    enabled: true
    labels:
      jobLabel: postgresql-runcounter
      "{{ prometheus_servicemonitor_label_name }}": "{{ prometheus_servicemonitor_labels.postgresql }}"
    jobLabel: jobLabel
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    labels:
      "{{ prometheus_rule_label_name }}": "{{ prometheus_rule_labels.postgresql }}"

networkPolicy:
  enabled: true
  metrics:
    enabled: true
