---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dune-daq
  namespace: {{ kafka.namespace }}
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  kafka:
    replicas: {{ kafka.replicas }}
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: WARN
    jvmOptions:
      -Xmx: 8192m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: true
        configuration:
          useServiceDnsDomain: true
    version: 3.4.0
    config:
      inter.broker.protocol.version: "3.4"

      log.retention.bytes: 6442450944 # no default upper size limit, set one
      default.replication.factor: {{ kafka.replicas }}
      offsets.topic.replication.factor: {{ kafka.replicas }}
      transaction.state.log.replication.factor: {{ kafka.replicas }}
{% if kafka.replicas < 3 %}
      # replication only makes sense if there are 3 or more brokers
      transaction.state.log.min.isr: 1
      min.insync.replicas: 1
{% else %}
      transaction.state.log.min.isr: {{ kafka.replicas - 1 }}
      min.insync.replicas: {{ kafka.replicas - 1 }}
{% endif %}
    storage:
      type: persistent-claim
      class: {{ kafka.storage_class }}
      size: {{ kafka.storage_size }}
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
{% if kafka.replicas < 3 %}
    replicas: 1
{% else %}
    replicas: 3
{% endif %}
    storage:
      type: persistent-claim
      class: {{ kafka.storage_class }}
      size: {{ kafka.zookeeper_storage_size }}
      deleteClaim: false
{% if not args.with_kafka_kraft %}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: zookeeper-metrics
          key: zookeeper-metrics-config.yml
{% endif %}
