---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ DUNE_kafka.name }}
  namespace: {{ DUNE_kafka.namespace }}
spec:
  entityOperator:
    userOperator: {}
    #topicOperator: {} # topicOperator not supported on KRaft
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  kafka:
    replicas: {{ DUNE_kafka.replicas }}
    resources:
      requests:
        cpu: 1
        memory: 8Gi # kafka with less than 8Gi is not recommended
      limits:
        cpu: 2
        memory: 12Gi
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: WARN
    jvmOptions:
      -Xms: 8192m
      -Xmx: 8192m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: true
        configuration:
          useServiceDnsDomain: true
    version: {{ DUNE_kafka.version }}
    config:
      inter.broker.protocol.version: "{{ DUNE_kafka.protocol_version }}"

      log.retention.bytes: 6442450944 # no default upper size limit, set to 6Gi
      default.replication.factor: {{ DUNE_kafka.replicas }}
      offsets.topic.replication.factor: {{ DUNE_kafka.replicas }}
      transaction.state.log.replication.factor: {{ DUNE_kafka.replicas }}
{% if DUNE_kafka.replicas < 3 %}
      # replication only makes sense if there are 3 or more brokers
      transaction.state.log.min.isr: 1
      min.insync.replicas: 1
{% else %}
      # replicate to n-1 for stability at small replica counts
      transaction.state.log.min.isr: {{ kafka.replicas - 1 }}
      min.insync.replicas: {{ kafka.replicas - 1 }}
{% endif %}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    storage: # no persistance requested
      type: ephemeral
  zookeeper: # this stanza is still required even in KRaft mode
{% if kafka.replicas < 3 %}
    replicas: 1
{% else %}
    replicas: 3
{% endif %}
    storage:
      type: ephemeral
