{% for thisone in prometheis %}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-{{ prometheis[thisone].name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-{{ prometheis[thisone].name }}
  namespace: {{ prometheis[thisone].namespace }}
...
{% endfor %}
