{% for thisone in prometheis %}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ prometheis[thisone].name }}
  namespace: {{ prometheis[thisone].namespace }}
  labels:
    app.kubernetes.io/instance: prometheus-{{ prometheis[thisone].name }}
    {{ prometheus_config_label_name }}: {{ prometheis[thisone].name }}
    prometheus: {{ prometheis[thisone].name }}
spec:
  alerting:
    alertmanagers: {{ prometheis[thisone].alertmanagers | tojson }}

  enableAdminAPI: false
  hostNetwork: false
  containers:
  - name: prometheus
    startupProbe:
      failureThreshold: 300

  # https://github.com/prometheus-operator/prometheus-operator/issues/5519
  securityContext:
    runAsNonRoot: true
    runAsUser: 65536
    runAsGroup: 65536
    fsGroup: 65536
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: RuntimeDefault

  portName: {{ prometheis[thisone].portName }}
  replicas: {{ prometheis[thisone].replicas }}
  retention: {{ prometheis[thisone].retention }}

  serviceAccountName: prometheus-{{ prometheis[thisone].name }}

  resources: {{ prometheis[thisone].resources | tojson }}
  affinity: {{ prometheis[thisone].affinity | tojson }}
  {% if prometheis[thisone].storage is defined %}
  storage: {{ prometheis[thisone].storage | tojson }}
  {% if prometheis[thisone].retentionSize is defined %}
  retentionSize: {{ prometheis[thisone].retentionSize | tojson }}
  {% endif %}
  {% endif %}


  serviceMonitorNamespaceSelector: {{ prometheis[thisone].serviceMonitorNamespaceSelector | tojson }}
  serviceMonitorSelector: {{ prometheis[thisone].serviceMonitorSelector | tojson }}
  podMonitorNamespaceSelector: {{ prometheis[thisone].podMonitorNamespaceSelector | tojson }}
  podMonitorSelector: {{ prometheis[thisone].podMonitorSelector | tojson }}
  probeNamespaceSelector: {{ prometheis[thisone].probeNamespaceSelector | tojson }}
  probeSelector: {{ prometheis[thisone].probeSelector | tojson }}
  ruleNamespaceSelector: {{ prometheis[thisone].ruleNamespaceSelector | tojson }}
  ruleSelector: {{ prometheis[thisone].ruleSelector | tojson }}
  scrapeConfigNamespaceSelector: {{ prometheis[thisone].scrapeConfigNamespaceSelector | tojson }}
  scrapeConfigSelector: {{ prometheis[thisone].scrapeConfigSelector | tojson }}
...
{% endfor %}
