---
deployments:
  - path: namespace
    alwaysDeploy: true

  - barrier: true
    message: We need a namespace to deploy into
    waitReadinessObjects:
      - kind: Namespace

  - path: metrics-server
    tags:
      - metrics

  - path: kube-state-metrics
    tags:
      - metrics
      - prometheus

  - path: prometheus-node-exporter
    tags:
      - metrics
      - node-exporter
      - prometheus

vars:
  - file: variables/metrics.yaml
