apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ monitoring.namespace }}

resources:
  - helm-rendered.yaml

commonLabels:
  app.kubernetes.io/component: {{ grafana.component_value }}
  app.kubernetes.io/instance: grafana-devel-other
