---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ DUNE_daqconfig.namespace }}

resources:
  - configservice.yml # https://github.com/DUNE-DAQ/microservices/tree/develop/config-service/configservice.yml
