---
metrics:
  enabled: true

% if inside_kind %}
hostUsers: true
{% else %}
hostUsers: false
{% endif %}

resources: # this is guess work
  limits:
    cpu: 250m
    memory: 96Mi
  requests:
    cpu: 100m
    memory: 96Mi

serviceMonitor:
  enabled: true
  additionalLabels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ kubernetes_labels.node_worker }}
              operator: Exists
