---
metrics:
  enabled: true

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 50Mi

serviceMonitor:
  enabled: true
  additionalLabels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}
