---
metrics:
  enabled: true

resources: # this is guess work
  limits:
    cpu: 250m
    memory: 96Mi
  requests:
    cpu: 100m
    memory: 96Mi

serviceMonitor:
  enabled: true
  additionalLabels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}

podDisruptionBudget:
  enabled: true
  maxUnavailable: 0
  unhealthyPodEvictionPolicy: AlwaysAllow

affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: {{ kubernetes_labels.node_worker }}
         operator: Exists
