---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: {{ monitoring.namespace }}
spec:
  refreshPolicy: OnChange
  secretStoreRef: {{ external_secrets.kubernetes_secretStore | tojson }}
  target:
    template:
      data:
        admin-user: admin
{% raw %}
        admin-password: "{{ .decoded }}"
{% endraw %}
  data:
    - secretKey: decoded
      remoteRef: {{ external_secrets.static_password | tojson }}
