helmChart:
  chartVersion: 75.10.0
  namespace: '{{ prometheus_operator_namespace }}'
  output: helm-rendered.yaml
  repo: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  releaseName: kube-prometheus-stack
  skipCRDs: true
  updateConstraints: ~75.x
