---
## 
fullnameOverride: "kube-prometheus-stack"

## Create default rules for monitoring the cluster
## 
defaultRules:
  create: true

kubeControllerManager:
  enabled: true
  service:
    enabled: true
    selector:
      component: kube-controller-manager
  serviceMonitor:
    enabled: true

kubeProxy:
  enabled: true
  service:
    enabled: true
    selector:
      k8s-app: kube-proxy
  serviceMonitor:
    enabled: true

kubeScheduler:
  enabled: true
  service:
    enabled: true
    selector:
      component: kube-scheduler
  serviceMonitor:
    enabled: true


## do create the prometheus-operator
##
prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
  networkPolicy:
    enabled: true
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 16Mi

## do not deploy a default monitoring setup
## we will manage it seperately
prometheus:
  enabled: false
alertmanager:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false

## do not deploy the grafana server here
## we will manage it seperately
grafana:
  enabled: false

## Make sure things have workable names
cleanPrometheusOperatorObjectNames: true
