helmChart:
  chartVersion: 88.5.3
  namespace: '{{ prometheus_operator_namespace }}'
  output: helm-rendered.yaml
  releaseName: kube-prometheus-stack
  repo: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  skipCRDs: true
