helmChart:
  chartName: kube-prometheus-stack
  chartVersion: 50.3.1
  namespace: '{{ prometheus_operator_namespace }}'
  output: helm-rendered.yaml
  releaseName: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  skipCRDs: true
  updateConstraints: ~50.x
