---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ prometheus_operator_namespace }}

resources:
  - helm-rendered.yaml

patches:
  - target:
      kind: PrometheusRule
      name: .*
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus-operator-validated: "true"
  - target:
      kind: serviceMonitor
    patch: |-
     - op: replace
       path: /metadata/namespace
       value: kube-system
  - target:
      kind: serviceMonitor
      name: kube-prometheus-stack-operator
    patch: |-
     - op: replace
       path: /metadata/namespace
       value: {{ prometheus_operator_namespace }}
