---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# this installs into several namespaces, don't force a single one here
# namespace: {{ prometheus_operator_namespace }}

resources:
  - helm-rendered.yaml

patches:
  - target:
      kind: PrometheusRule
      name: .*
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          prometheus-operator-validated: "true"
