---
deployments:
  - path: config

  - barrier: true
    message: Make sure the config elements exist before we use them

  - path: postgresql

ignoreForDiff: # don't keep changing the postgresql password
  - kind: Secret
    name: runcounter-postgresql-svcbind-postgres
    fieldPath: .data.password
  - kind: Secret
    name: runcounter-postgresql-svcbind-postgres
    fieldPath: .data.uri
