---
DUNE_daqconfig:
  namespace: daqconfig
  mongodb_authentication:
    rootUser: root
    rootPassword: {{ args.daqconfig_mongodb_root_password }}
    usernames:
    - daqconfig
    passwords:
    - {{ args.daqconfig_mongodb_daqconfig_password }}
    databases:
    - daqconfigdb
