---
resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 20m
    memory: 32Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  labels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}
