---
resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 10m
    memory: 16Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  labels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}
