config:
{%- if 'pocket' in target.name %}
  inClusterContextName: pocket
{% endif %}
  unsafeUseServiceAccountToken: true

% if inside_kind %}
hostUsers: true
{% else %}
hostUsers: false
{% endif %}

staticPlugins:
  enabled: false

serviceAccount:
  name: headlamp-read-only
clusterRoleBinding:
  clusterRoleName: read-only-user

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  privileged: false
  runAsUser: 1002
  runAsGroup: 1002
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

resources: # this is guess work
 limits:
   cpu: 1
   memory: 1Gi
 requests:
   cpu: 100m
   memory: 128Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ kubernetes_labels.node_worker }}
              operator: Exists

podDisruptionBudget:
  enabled: true

extraManifests:
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: headlamp-extra-rights
    rules:
      - apiGroups: [""]
        resources: ["services/proxy", "pods/log"]
        verbs: ["get", "list"]
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: headlamp-extra-rights
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: headlamp-extra-rights
    subjects:
      - kind: ServiceAccount
        name: headlamp-read-only
        namespace: headlamp
