---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka.yml

patches:
  - target:
      group: kafka.strimzi.io
      version: v1
      kind: Kafka
    patch: |-
      - op: replace
        path: /spec/entityOperator/template/pod/hostUsers
{% if inside_kind %}
        value: true
{% else %}
        value: false
{% endif %}
      - op: replace
        path: /spec/kafkaExporter/template/pod/hostUsers
{% if inside_kind %}
        value: true
{% else %}
        value: false
{% endif %}
      - op: replace
        path: /spec/kafka/template/pod/hostUsers
{% if inside_kind %}
        value: true
{% else %}
        value: false
{% endif %}
{% if dune_online.kafka.replicas > 1 %}
      - op: replace
        path: /spec/cruiseControl/template/pod/hostUsers
{% if inside_kind %}
        value: true
{% else %}
        value: false
{% endif %}
{% endif %}
