---
setDefaultUser:
  enabled: true
  user:
    username: {{ OPMON_influxdb.admin_username }}
    password: {{ OPMON_influxdb.admin_password }}

env: {{ OPMON_influxdb.env | tojson }}

persistence:
  enabled: true
  size: 8Gi # this size is guess work
  storageClass: {{ local_path_provisioner.storage_class_name }}

resources: # this is guess work
  requests:
    cpu: 10m
    memory: 16Mi

securityContext:
  runAsUser: 1999
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ kubernetes_worker_label }}
          operator: Exists
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions: # try to schedule away from Kafka
          - key: "strimzi.io/cluster"
            operator: In
            values:
            - "{{ dunedaq.kafka.name }}"
        topologyKey: kubernetes.io/hostname
