---
deployments:
  - path: namespace
    alwaysDeploy: true

  - barrier: true
    message: We need a namespace to deploy into

  - path: headlamp
  - path: kubeconfig

vars:
  - file: variables/headlamp.yaml
