apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pcm-kubernetes.yaml

patches:
  - target:
      kind: PodMonitor
    patch: |-
      - op: remove
        path: /metadata/labels/{{ prometheus_podmonitor_label_name }}
      - op: add
        path: /metadata/labels/{{ prometheus_podmonitor_label_name }}
        value: {{ prometheus_podmonitor_labels.system }}
