apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pcm-kubernetes.yaml

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations/kluctl.io~1wait-readiness
        value: "true"
  - target:
      kind: PodMonitor
    patch: |-
      - op: add
        path: /metadata/labels/{{ prometheus_podmonitor_label_name | replace("/", "~1") }}
        value: {{ prometheus_podmonitor_labels.system }}
  - target:
      kind: DaemonSet
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
  - target: # eventually drop this once we are all k8s
      kind: DaemonSet
    patch: |-
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
