---
deployments:
  - path: namespace

  - barrier: true

  - path: kafka-topic
  - path: postgresql

  - barrier: true
    message: Let services all catch up

  - path: ers-dbwriter
  - path: ers-protobuf-dbwriter

vars:
  - file: variables/ers.yaml
