---
auth:
  username: "{{ DUNE_ers.postgresql_database_username }}"
  password: "{{ DUNE_ers.postgresql_database_password }}"
  database: "{{ DUNE_ers.postgresql_database_name }}"

architecture: standalone

serviceBindings:
  enabled: true

primary:
  initdb:
    args: '--data-checksums --locale=en_US.UTF-8'

  persistence: # this is guess work
    size: 4Gi

metrics:
  enabled: true
  resources: # this is guess work
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  serviceMonitor:
    enabled: true
    labels:
      jobLabel: postgresql-ers
      "{{ prometheus_servicemonitor_label_name }}": "{{ prometheus_servicemonitor_labels.postgresql }}"
    jobLabel: jobLabel
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    labels:
      "{{ prometheus_rule_label_name }}": "{{ prometheus_rule_labels.postgresql }}"

networkPolicy:
  enabled: true
  metrics:
    enabled: true
