---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  annotations:
    kluctl.io/skip-delete: "true"
  labels: # this needs unrestricted rights to work
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
