---
deployments:
  - path: namespace

  - barrier: true

  - path: kafka-topic
  - path: influxdb

  - barrier: true
    message: Let services all catch up

  - path: telegraf

vars:
  - file: variables/opmon.yaml
  - file: variables/telegraf.yaml
  - file: variables/influxdb.yaml
