---
deployments:
  - path: namespace
    alwaysDeploy: true
    skipDeleteIfTags: true

  - barrier: true

  - path: cvmfs-csi
    skipDeleteIfTags: true

  - barrier: true
    message: wait for cvmfs-csi to settle

vars:
  - file: variables/cvmfs_csi.yaml
