---
deployments:
  - path: namespace

  - barrier: true

  - path: mongodb

  - barrier: true
    message: make sure mongodb is setup for daqconfig container

  - path: mongo-express
  - path: daqconfig

vars:
  - file: variables/daqconfig.yaml

ignoreForDiff:
  - kind: Secret # don't constantly change the metrics user password
    name: mongodb
    fieldPath: .data["mongodb-metrics-password"]
