yamlApplicationConfig:
  kafka:
    clusters:
      - name: {{ dunedaq.kafka.name }}
        bootstrapServers: {{ dunedaq.kafka.name }}-kafka-bootstrap:9092
        readOnly: false
#        properties:
#          security.protocol: SASL_PLAINTEXT
#          sasl.mechanism: PLAIN
#          sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="ddd" password="eee";

env:
  - name: DYNAMIC_CONFIG_ENABLED
    value: "true"

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 1m
    memory: 16Mi

podSecurityContext: # https://github.com/provectus/kafka-ui-charts/pull/10
  fsGroup: 101
securityContext: # https://github.com/provectus/kafka-ui-charts/pull/10
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 100
  seccompProfile:
    type: RuntimeDefault

affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: {{ kubernetes_worker_label }}
         operator: Exists
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions: # try to schedule near Kafka
          - key: "strimzi.io/cluster"
            operator: In
            values:
            - "{{ dunedaq.kafka.name }}"
        topologyKey: kubernetes.io/hostname
