---
deployments:
  - path: namespace

  - barrier: true

{% if with_dune_runservices_db_as == 'postgresql' %}
  - path: postgresql
{% elif  with_dune_runservices_db_as == 'oracle' %}
  - path: oracle
{% endif %}

  - barrier: true
    message: make sure database is up

  - path: runnumber-rest
  - path: runregistry-rest

vars:
  - file: variables/runservices.yml

ignoreForDiff: # don't keep changing the postgresql password
  - kind: Secret
    name: runservices-postgresql-svcbind-postgres
    fieldPath: .data.password
  - kind: Secret
    name: runservices-postgresql-svcbind-postgres
    fieldPath: .data.uri
  - kind: Secret
    name: runservices-postgresql
    fieldPath: .data["postgres-password"]
