---
deployments:
  - path: namespace

  - barrier: true

{% if with_dune_runservices_db_as == 'postgresql' %}
  - include: postgresql # FIXME for sqlalchemy
{% elif  with_dune_runservices_db_as == 'oracle' %}
  - path: oracle
{% endif %}

  - barrier: true
    message: make sure database is up

  - path: runnumber-rest
  - path: runregistry-rest

vars:
  - file: variables/runservices.yml
