---
deployments:
  - path: namespace

  - barrier: true

  - include: postgresql

  - barrier: true
    message: make sure database is up

  - path: runnumber-rest
  - path: runregistry-rest

vars:
  - file: variables/runservices.yml
