apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-test-pvc
  namespace: "{{ cvmfs_csi.namespace }}"
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: cvmfs
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cvmfs-verifier-job
  namespace: "{{ cvmfs_csi.namespace }}"
  annotations:
    kluctl.io/wait-readiness: "false"
spec:
  backoffLimit: 7 # Too many levels of symbolic links, means we must retry
  template:
    spec:
      restartPolicy: Never
      hostUsers: true # cvmfs can't chown
      containers:
        - name: cvmfs-verifier
          image: docker.io/library/busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e
              repo="config-osg.opensciencegrid.org"
              echo "=== Filesystem details ==="
              df -h /cvmfs
              echo ""
              echo "=== Waiting for autofs setup ==="
              sleep 5
              ls -lah /cvmfs || true
              echo ""
              echo "=== Checking CVMFS connectivity ==="
              for i in $(seq 1 9); do
                sleep 3
                echo "Attempt $i: CVMFS repo ${repo}"
                ls -lahF /cvmfs/${repo} && break
              done
              echo ""
              echo "Please review results"
              ls -lahF /cvmfs/${repo}
          volumeMounts:
            - name: cvmfs-vol
              mountPath: /cvmfs
              readOnly: true
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 64Mi
              cpu: 100m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 11000
            runAsGroup: 11000
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: cvmfs-vol
          persistentVolumeClaim:
            claimName: cvmfs-test-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ kubernetes_labels.node_worker }}
                    operator: Exists
