fullnameOverride: {{ dune_online_runservices.database.postgresql.deployment }}-prometheus-postgresql-exporter

config:
  datasource:
    host: {{ dune_online_runservices.database.postgresql.deployment }}-r.{{ dune_online_runservices.namespace }}.svc # 'r' targets any instance, 'ro' targets read-only instances only
    user: postgresql_exporter
    sslmode: require
    database: {{ dune_online_runservices.database.postgresql.database }}
    passwordSecret:
      name: {{ dune_online_runservices.database.postgresql.deployment }}-postgresql-exporter-password
      key: password

networkPolicy:
  enabled: true

podMonitor:
  enabled: true
  labels:
    {{ prometheus_podmonitor_label_name }}: {{ prometheus_podmonitor_labels.postgresql }}

podDisruptionBudget:
  enabled: true
  unhealthyPodEvictionPolicy: AlwaysAllow

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 100m
    memory: 128Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ kubernetes_labels.node_worker }}
          operator: Exists
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: cnpg.io/cluster
                operator: In
                values:
                  - my-cluster
              - key: role
                operator: In
                values:
                  - replica
          topologyKey: kubernetes.io/hostname
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: cnpg.io/cluster
                operator: In
                values:
                  - my-cluster
              - key: role
                operator: In
                values:
                  - primary
          topologyKey: kubernetes.io/hostname
