---
deployments:
  - path: namespace

  - barrier: true

  - include: postgresql

  - barrier: true
    message: make sure database is up

  - path: runnumber-rest
  - path: runregistry-rest

vars:
  - file: variables/runcounter.yml

ignoreForDiff: # don't keep changing the postgresql password
  - kind: Secret
    name: runcounter-postgresql-svcbind-postgres
    fieldPath: .data.password
  - kind: Secret
    name: runcounter-postgresql-svcbind-postgres
    fieldPath: .data.uri
