{% if with_dune_daq_services %}
{% if with_dune_daqconfig %}
{% if with_mongo_express %}
---
# do we really need this?
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mongo-express
    app.kubernetes.io/instance: mongo-express
    app.kubernetes.io/name: mongo-express
  name: mongo-express-nodeport
  namespace: daqconfig
spec:
  ports:
  - name: mongo-express
    port: 8081
    protocol: TCP
    targetPort: mongo-express
    nodePort: 31012
  selector:
    app.kubernetes.io/component: mongo-express
    app.kubernetes.io/instance: mongo-express
    app.kubernetes.io/name: mongo-express
  type: NodePort
{% endif %}
{% endif %}
{% endif %}
