{% if args.with_python-tiny-proxy %}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: python-tiny-proxy
    app.kubernetes.io/component: python-tiny-proxy
  name: python-tiny-proxy-nodeport
  namespace: python-tiny-proxy
spec:
  ports:
    - name: socks5
      protocol: TCP
      port: 1080
      targetPort: socks5
      nodePort: 31000
  selector:
    app.kubernetes.io/app: python-tiny-proxy
    app.kubernetes.io/component: python-tiny-proxy
  type: NodePort
{% endif %}
