{% if with_dune_daq_services %}
{% if with_dune_runservices %}
--- 
apiVersion: v1
kind: Service
metadata:    
  name: runnumber-rest-nodeport
  labels:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  namespace: runservices
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30016
  selector:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
{% endif %}
{% endif %}
