---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-runservices
  namespace: {{ dune_online_runservices.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
