---
# Apache Kafka is "stable" with KRaft but
# you cannot upgrade from one version of kafka to the next with Kraft
# so, unless we want to lockin forever no +UseKRaft for us
# in production right now, but it is fine for disposable dev
{% if args.with_kafka_kraft %}
featureGates: '+StableConnectIdentities,+UseKRaft'
{% else %}
featureGates: '+StableConnectIdentities'
{% endif %}

watchAnyNamespace: true

extraEnvs:
  - name: STRIMZI_POD_SECURITY_PROVIDER_CLASS
    value: restricted

dashboards:
  enabled: true
  label: {{ grafana_dashboard_label_name }}
  labelValue: {{ grafana_dashboard_label_value }}
  annotations:
    {{ grafana_dashboard_folder_annotation }}: Kafka
