---
# Apache Kafka is "stable" with KRaft but
# you cannot upgrade from one version of kafka to the next with Kraft
{% if strimzi.with_kafka_kraft %}
featureGates: '+UseKRaft,+KafkaNodePools'
{% else %}
featureGates: ''
{% endif %}

watchAnyNamespace: true

affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: {{ kubernetes_label.worker }}
         operator: Exists

extraEnvs:
  - name: STRIMZI_POD_SECURITY_PROVIDER_CLASS
    value: restricted

dashboards:
  enabled: true
  label: {{ grafana_dashboard_label_name }}
  labelValue: {{ grafana_dashboard_label_value }}
  annotations:
    {{ grafana_dashboard_folder_annotation }}: Kafka
