---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ strimzi.namespace }}

resources:
  - helm-rendered.yaml

# disable dashboards for components we are not using
patches:
{% if strimzi.with_kafka_kraft %}
  - target:
      kind: ConfigMap
      name: strimzi-zookeeper
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
{% else %}
  - target:
      kind: ConfigMap
      name: strimzi-kraft
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
{% endif %}
{% if not kafka.with_bridge %}
  - target:
      kind: ConfigMap
      name: strimzi-kafka-bridge
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
{% endif %}
{% if not kafka.with_connect %}
  - target:
      kind: ConfigMap
      name: strimzi-kafka-connect
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
{% endif %}
{% if not kafka.with_cruisecontrol %}
  - target:
      kind: ConfigMap
      name: strimzi-cruise-control
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
{% endif %}
{% if not kafka.with_mirrormaker %}
  - target:
      kind: ConfigMap
      name: strimzi-kafka-mirror-maker-2
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
{% endif %}
  - target:
      kind: ConfigMap
      name: strimzi-kafka-oauth
    patch: |-
      - op: remove
        path: /metadata/labels/{{ grafana_dashboard_label_name }}
