---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  name: runnumber-rest
  namespace: {{ DUNE_runservices.namespace }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/app: runnumber-rest
      app.kubernetes.io/component: runnumber-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/app: runnumber-rest
        app.kubernetes.io/component: runnumber-rest
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: {{ kubernetes_label.worker }}
               operator: Exists
      containers:
      - image: ghcr.io/dune-daq/pocket-runserv-rest:0.1 # this tag is different than standard
        name: runnumber-rest
        env:
        - name: MICROSERVICE
          value: runnumber-rest
        # envFrom:
        # - secretRef:
        #     name: run-db-secret
        # volumeMounts:
        #   - name: tnsnames-ora
        #     mountPath: /etc/tnsnames.ora
        #     subPath: tnsnames.ora
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          seccompProfile:
            type: RuntimeDefault
      # volumes:
      #   - name: tnsnames-ora
      #     configMap:
      #       name: tnsnames-ora
      #       items:
      #        - key: tnsnames.ora
      #          path: tnsnames.ora
      securityContext:
        fsGroup: 11000
