---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ nfs_subdir_external_provisioner.namespace }}"
  labels: # needs chown as root
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
