---
deployments:
  - path: grafana-dashboards

  - include: connectionservice
  - include: daqconfig
  - include: runcounter

{% if args.with_cvmfs_csi %}
  - path: cvmfs-storageclass
    tags:
      - cvmfs
      - storage
{% endif %}

  - path: node-ports

vars:
  - file: variables/dunedaq.yaml
