---
# Modified from https://github.com/DUNE-DAQ/connectivityserver/blob/develop/deploy/connectivityserver.yaml
#
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: {{ DUNE_connectionservice.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: connectionservice
    app.kubernetes.io/component: connectionservice
    app.kubernetes.io/instance: {{ target.name }}
  name: connectionservice
  namespace: {{ DUNE_connectionservice.namespace }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/app: connectionservice
      app.kubernetes.io/component: connectionservice
  template:
    metadata:
      labels:
        app.kubernetes.io/app: connectionservice
        app.kubernetes.io/component: connectionservice
        app.kubernetes.io/instance: {{ target.name }}
    spec:
      containers:
      - image: docker.io/dunedaq/pocket-connectivityserver:1.0.0
        name: connectionservice
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          runAsUser: 10000
          runAsGroup: 10000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 10000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: connectionservice
    app.kubernetes.io/component: connectionservice
    app.kubernetes.io/instance: {{ target.name }}
  name: connectionservice
  namespace: {{ DUNE_connectionservice.namespace }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/app: connectionservice
    app.kubernetes.io/component: connectionservice
    app.kubernetes.io/instance: {{ target.name }}
  type: ClusterIP
