---
deployments:
  - path: namespace
    alwaysDeploy: true

  - barrier: true
    message: We need a namespace to deploy into

  - path: metrics
    tags:
      - monitoring

  - path: strimzi
    waitReadiness: true

  - barrier: true
    message: strimzi needs to settle (about 2m)

vars:
  - file: variables/strimzi.yaml
