---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: tinyproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: tinyproxy
    app.kubernetes.io/component: tinyproxy
  name: tinyproxy
  namespace: tinyproxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: tinyproxy
      app.kubernetes.io/component: tinyproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/app: tinyproxy
        app.kubernetes.io/component: tinyproxy
    spec:
      containers:
      - image: ghcr.io/dune-daq/tinyproxy:latest
        imagePullPolicy: Always
        name: tinyproxy
        ports:
        - containerPort: 8888
          name: socks5
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 8Mi
            cpu: 5m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          runAsUser: 10000
          runAsGroup: 10000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 10000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: tinyproxy
    app.kubernetes.io/component: tinyproxy
  name: tinyproxy
  namespace: tinyproxy
spec:
  ports:
  - name: socks5
    protocol: TCP
    port: 1080 # 1080 is the ICANN socks5 port
    targetPort: 8888
  selector:
    app.kubernetes.io/app: tinyproxy
    app.kubernetes.io/component: tinyproxy
  type: ClusterIP
