{{- if .Values.automountStorageClass.create }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.automountStorageClass.name }}
  labels:
    {{- include "cvmfs-csi.common.metaLabels" .  | nindent 4 }}
provisioner: {{ .Values.csiDriverName }}
{{- end }}
