{{- range $repo := .Values.specificRepositoryStorageClasses -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $repo.name }}
  labels:
    {{- include "cvmfs-csi.common.metaLabels" $  | nindent 4 }}
provisioner: {{ $.Values.csiDriverName }}
parameters:
  repository: {{ $repo.repository }}
{{ end }}
