---
# this is such a hack!!!
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ dune_online_runservices.database.postgresql.deployment }}-{{ dune_online_runservices.database.postgresql.owner }}-password
  namespace: {{ dune_online_runservices.namespace }}
spec:
  secretStoreRef: {"kind": "ClusterSecretStore", "name": "static-passwords"}
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
{% raw %}
        uri: "{{ .transport }}://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}?{{ .args }}"
{% endraw %}
  data:
    - secretKey: password
      remoteRef:
        key: runservices-oracle-static-password
        property: password
    - secretKey: host
      remoteRef:
        key: runservices-oracle-static-fields
        property: host
    - secretKey: port
      remoteRef:
        key: runservices-oracle-static-fields
        property: port
    - secretKey: username
      remoteRef:
        key: runservices-oracle-static-fields
        property: username
    - secretKey: transport
      remoteRef:
        key: runservices-oracle-static-fields
        property: transport
    - secretKey: args
      remoteRef:
        key: runservices-oracle-static-fields
        property: args
