---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ dune_online_runservices.database.postgresql.deployment }}-{{ dune_online_runservices.database.postgresql.owner }}-password # this is such a hack!!!
  namespace: {{ dune_online_runservices.namespace }}
spec:
  secretStoreRef: {"kind": "ClusterSecretStore", "name": "static-passwords"}
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: {{ dune_online_runservices.database.oracle.owner }}
{% raw %}
        password: "{{ .password }}"
{% endraw %}
        database: {{ dune_online_runservices.database.oracle.database }}
        host: {{ dune_online_runservices.database.oracle.host }}
        port: "{{ dune_online_runservices.database.oracle.port }}"
        uri: "oracle://{{ dune_online_runservices.database.oracle.owner }}:{% raw %}{{ .password }}{% endraw %}@{{ dune_online_runservices.database.oracle.host }}:{{ dune_online_runservices.database.oracle.port }}?{{ dune_online_runservices.database.oracle.deployment }}"
        pyuri: "oracle+oracledb://{{ dune_online_runservices.database.oracle.owner }}:{% raw %}{{ .password }}{% endraw %}@{{ dune_online_runservices.database.oracle.host }}:{{ dune_online_runservices.database.oracle.port }}?{{ dune_online_runservices.database.oracle.deployment }}"
  data:
    - secretKey: password
      remoteRef:
        key: runservices-oracle-static-password
        property: password
