---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ minio.operator_namespace }}
  labels: # https://github.com/minio/operator/pull/1653
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
