---
deployments:
  - path: namespace
    alwaysDeploy: true
    skipDeleteIfTags: true

  - barrier: true

  - path: cert-manager
    waitReadiness: true

  - barrier: true

  - path: ca

  - barrier: true

  - path: trust-manager
    waitReadiness: true

vars:
  - file: variables/certmanager.yaml
