---
deployments:
  - path: namespace
    alwaysDeploy: true
    skipDeleteIfTags: true

  - barrier: true

  - path: cert-manager
    skipDeleteIfTags: true
    waitReadiness: true

  - barrier: true

  - path: ca

vars:
  - file: variables/certmanager.yaml
