{% for thistopic in DUNE_opmon.kafka_topics %}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ dunedaq.kafka.name }}
  name: {{ thistopic }}
  namespace: {{ dunedaq.kafka.namespace }}
spec: {}
...
{% endfor %}
