---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-kubeconfig
  namespace: {{ headlamp.namespace }}
spec:
  refreshPolicy: OnChange
  secretStoreRef: {{ external_secrets.kubernetes_secretStore | tojson }}
  target:
    template:
      data:
        config: |
          apiVersion: v1
          kind: Config
          current-context: kubernetes
          clusters:
          - name: kubernetes
            cluster:
{%- raw %}
              certificate-authority-data: {{ index . "ca.crt" | b64enc }}
{%- endraw %}
              server: https://kubernetes.default.svc.cluster.local
          contexts:
          - context:
              cluster: kubernetes
              user: read-only-user
              namespace: default
{%- if 'pocket' in target.name %}
            name: pocket
{%- else %}
            name: "{{ target.name }}"
{% endif %}

          users:
          - name: read-only-user
            user:
{%- raw %}
              token: {{ .token }}
{%- endraw %}
  dataFrom:
  - extract:
      key: read-only-user-token
