---
enableNodeFeatureApi: {{ node_feature_discovery.enableNodeFeatureApi }}

master:
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 16Mi

worker:
  config:
    core:
     sleepInterval: {{ node_feature_discovery.worker.updateInterval }}
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 16Mi

topologyUpdater:
  enable: {{ node_feature_discovery.topologyUpdater.enable }}
  updateInterval:  {{ node_feature_discovery.topologyUpdater.updateInterval }}
  createCRDs: {{ node_feature_discovery.topologyUpdater.enable }}
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 16Mi

topologyGC:
  enable: {{ node_feature_discovery.topologyUpdater.enable }}
  interval: {{ node_feature_discovery.topologyUpdater.updateInterval }}
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 16Mi

# TODO: figure out cert-manager
tls:
  enable: false
  certManager: false
