---
enableNodeFeatureApi: {{ node_feature_discovery.enableNodeFeatureApi }}

prometheus:
  enable: true
  labels:
    {{ prometheus_podmonitor_label_name }}: {{ prometheus_podmonitor_labels.system }}

master:
  revisionHistoryLimit: 3
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 128Mi
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: {{ kubernetes_label.worker }}
           operator: Exists
gc:
  revisionHistoryLimit: 3
  interval: {{ node_feature_discovery.worker.updateInterval }}
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 64Mi
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: {{ kubernetes_label.worker }}
           operator: Exists

worker:
  config:
    core:
     sleepInterval: {{ node_feature_discovery.worker.updateInterval }}
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 32Mi

topologyUpdater:
  enable: {{ node_feature_discovery.topologyUpdater.enable }}
  updateInterval:  {{ node_feature_discovery.topologyUpdater.updateInterval }}
  createCRDs: {{ node_feature_discovery.topologyUpdater.enable }}
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 32Mi
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: {{ kubernetes_label.worker }}
           operator: Exists

topologyGC:
  enable: {{ node_feature_discovery.topologyUpdater.enable }}
  interval: {{ node_feature_discovery.topologyUpdater.updateInterval }}
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 10m
      memory: 32Mi
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: {{ kubernetes_label.worker }}
           operator: Exists

# TODO: figure out cert-manager
tls:
  enable: false
  certManager: false
