apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-rendered.yaml

commonLabels:
  app.kubernetes.io/component: node-feature-discovery
  app.kubernetes.io/instance: node-feature-discovery
