---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elisa-logbook-secret
  namespace: {{ dune_online.elisa_logbook.namespace }}
spec:
  secretStoreRef: {"kind": "ClusterSecretStore", "name": "static-passwords"}
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
{% raw %}
        username: "{{ .username }}"
        password: "{{ .password }}"
{% endraw %}
  data:
    - secretKey: username
      remoteRef:
        key: elisa-logbook-static
        property: username
    - secretKey: password
      remoteRef:
        key: elisa-logbook-static
        property: password
