---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    {{ grafana_datasource_label_name }}: {{ grafana_datasource_label_value }}
  name: grafana-datasource-{{ dune_online_opmon.influxdb_v1.database_name | replace("_","-") }}
  namespace: {{ dune_online_opmon.namespace }}
spec:
  secretStoreRef: {{ external_secrets.kubernetes_secretStore | tojson }}
  target:
    template:
      metadata:
        labels:
          {{ grafana_datasource_label_name }}: {{ grafana_datasource_label_value }}
      data:
        datasource_influxdbv1_{{ dune_online_opmon.influxdb_v1.database_name }}.yaml: |-
          apiVersion: 1
          datasources:
          - name: InfluxKafka
            uid: InfluxKafka
            type: influxdb
            access: proxy
            database: {{ dune_online_opmon.influxdb_v1.database_name }}
            url:  "http://opmon-influxdb.{{ dune_online_opmon.namespace }}.svc:8086" # my heart breaks without ssl
            jsonData:
              httpMode: POST
            basicAuth: true
            basicAuthUser: readonly
            secureJsonData:
{% raw %}
              basicAuthPassword: "{{ .password }}"
{% endraw %}
  data:
    - secretKey: password
      remoteRef: {{ external_secrets.static_password | tojson }}
