---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdbv1-{{ dune_online_opmon.influxdb_v1.read_write_username }}-password
  namespace: {{ dune_online_opmon.namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    creationPolicy: Orphan
    template:
      type: kubernetes.io/basic-auth
      data:
        influxdb-user: {{ dune_online_opmon.influxdb_v1.read_write_username }}
        username: {{ dune_online_opmon.influxdb_v1.read_write_username }}
{% raw %}
        influxdb-password: "{{ .uuid }}"
        password: "{{ .uuid }}"
{% endraw %}
        database: {{ dune_online_opmon.influxdb_v1.database_name }}
        host: opmon-influxdb.{{ dune_online_opmon.namespace }}.svc
        port: '8086'
        uri: "influxdb://{{ dune_online_opmon.influxdb_v1.read_write_username }}:{% raw %}{{ .uuid }}{% endraw %}@opmon-influxdb.{{ dune_online_opmon.namespace }}.svc:8086/{{ dune_online_opmon.influxdb_v1.database_name }}"
  dataFrom:
    - sourceRef:
        generatorRef: {{ external_secrets.uuid | tojson }}
