---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdbv1-readonly-password
  namespace: {{ dune_online_opmon.namespace }}
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef: {{ external_secrets.kubernetes_secretStore | tojson }}
  target:
    creationPolicy: Orphan
    template:
      type: kubernetes.io/basic-auth
      data:
        username: readonly
{% raw %}
        password: "{{ .password }}"
{% endraw %}
        database: {{ dune_online_opmon.influxdb_v1.database_name }}
        host: opmon-influxdb.{{ dune_online_opmon.namespace }}.svc
        port: '8086'
        uri: "influxdb://readonly:{% raw %}{{ .password }}{% endraw %}@opmon-influxdb.{{ dune_online_opmon.namespace }}.svc:8086/{{ dune_online_opmon.influxdb_v1.database_name }}"
  data:
    - secretKey: password
      remoteRef: {{ external_secrets.static_password | tojson }}
