---
deployments:
  - path: debug
    alwaysDeploy: true
    skipDeleteIfTags: true

  - path: ro-cluster-role
    alwaysDeploy: true
    skipDeleteIfTags: true

  - include: metrics
    tags:
      - metrics
      - monitoring

  - barrier: true
    message: metrics need to settle so we can setup HPAs

  - path: dns-autoscaler

  - include: external-secrets
    tags:
      - secrets

  - include: prometheus
    tags:
      - metrics
      - monitoring

  - include: node-feature-discovery

  - barrier: true
    message: Make sure baseline is completely loaded
