---
deployments:
  - include: cert-manager-ca
    tags:
      - pki
      - tls

  - include: metrics
    tags:
      - metrics
      - monitoring

  - barrier: true
    message: metrics need to settle so we can setup HPAs

  - path: dns-autoscaler

  - include: external-secrets
    tags:
      - secrets

  - include: prometheus
    tags:
      - metrics
      - monitoring

  - barrier: true
    message: Make sure baseline is completely loaded
