---
deployments:
  - include: local-storage
    skipDeleteIfTags: true
    tags:
      - storage

  - include: metrics
    skipDeleteIfTags: true
    tags:
      - metrics
      - monitoring

{% if args.with_dns_autoscaler %}
  - barrier: true
    message: metrics need to settle so we can setup HPAs

  - path: dns-autoscaler
    skipDeleteIfTags: true
{% endif %}

  - include: prometheus
    tags:
      - metrics
      - monitoring

  - barrier: true
    message: Make sure baseline is completely loaded
