---
deployments:
{% if args.with_strimzi_kafka_operator %}
  - include: kafka
    tags:
      - strimzi
{% endif %}

#{% if args.with_minio_operator %}
#  - include: minio
#    tags:
#      - storage
#{% endif %}

# operators should always end in a barrier
  - barrier: true
    message: make sure operators have time to settle
