---
deployments:
{% if with_strimzi_kafka_operator %}
  - include: kafka
    tags:
      - strimzi
{% endif %}

# operators should always end in a barrier
  - barrier: true
    message: make sure operators have time to settle
