---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-ers
  namespace: {{ dune_online_ers.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
