---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ dune_online_opmon.namespace }}

resources:
  - opmon-dbwriter-deployment.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: {{ dune_online.unified_microservices.image }}:{{ dune_online.unified_microservices.tag }}
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: {{ dune_online.kafka.name}}-kafka-bootstrap.{{ dune_online.kafka.namespace }}.svc:9092
      - op: remove
        path: /spec/template/spec/containers/0/env/2/value
      - op: add
        path: /spec/template/spec/containers/0/env/2/valueFrom
        value: { 'secretKeyRef': { 'name': 'influxdbv1-{{ dune_online_opmon.influxdb_v1.read_write_username }}-password', 'key': 'influxdb-user' }}
      - op: remove
        path: /spec/template/spec/containers/0/env/3/value
      - op: add
        path: /spec/template/spec/containers/0/env/3/valueFrom
        value: { 'secretKeyRef': { 'name': 'influxdbv1-{{ dune_online_opmon.influxdb_v1.read_write_username }}-password', 'key': 'influxdb-password' }}
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: opmon-influxdb.{{ dune_online_opmon.namespace }}.svc
      - op: replace
        path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0/key
        value: {{ kubernetes_labels.node_worker }}
  - target:
      kind: Namespace
    patch: |-
      $patch: delete
      kind: Kustomization
      metadata:
        name: DOES NOT MATTER
