---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ felix_plugin.namespace }}
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
    kluctl.io/wait-readiness: "true"
  labels: # requires root access -> mknod, cap_sysadmin
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
