---
deployments:
  - path: namespace

  - barrier: true

  - path: mongodb

  - barrier: true
    message: make sure mongodb is setup for daqconfig container

{% if with_mongo_express %}
  - path: mongo-express
{% endif %}

  - path: daqconfig

vars:
  - file: variables/daqconfig.yaml

ignoreForDiff:
  - kind: Secret # don't constantly change the metrics user password
    name: daqconfig-mongodb
    fieldPath: .data["mongodb-metrics-password"]
