---
deployments:
{% if with_dune_daq_services %}
{% if with_grafana_dune_dashboards %}
  - path: grafana-dashboards
{% endif %}

{% if with_dune_connectionservice %}
  - include: connectionservice
{% endif %}
{% if with_dune_daqconfig %}
  - include: daqconfig
{% endif %}
{% if with_dune_runservices %}
  - include: runservices
{% endif %}
{% if with_dune_kafka %}
  - include: kafka
{% endif %}

{% if with_cvmfs_csi %}
  - path: cvmfs_storageclass
    tags:
      - cvmfs
      - storage
{% endif %}

{% if with_dune_ers %}
  - include: ers
{% endif %}
{% if with_dune_opmon %}
  - include: opmon
{% endif %}
{% endif %}

  - barrier: true
    message: Let services all catch up

vars:
  - file: variables/dunedaq.yaml
