---
deployments:
  - path: namespace
    alwaysDeploy: true

  - include: api

  - barrier: true
    message: The elisa log book API needs to settle

{% for thishardware in dune_online.elisa_logbook.hardware_types %}
  - path: elisa_logbook_api
    vars:
      - values:
          thishardware: {{ thishardware }}
          logbooktype: production

  - path: elisa_logbook_nodeports
    vars:
      - values:
          thishardware: {{ thishardware }}
          logbooktype: production
          baseport: 3190
          service_count: {{ loop.index0 }}
{% endfor %}
