---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-rendered.yaml

patches:
  - target:
      kind: StatefulSet
      name: opmon-influxdb
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value: { fsGroup: 1999 }
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value: { runAsUser: 1999, runAsGroup: 1999, runAsNonRoot: true, allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, seccompProfile: { type: RuntimeDefault }, capabilities: { drop: [ ALL ] } }
