---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dunedaq.opensciencegrid.org
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1 # any non-zero value
  storageClassName: dunedaq.opensciencegrid.org
