---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ ERS_telegraf.namespace }}

resources:
  - namespace.yml
  - cvmfs-dunedaq.opensciencegrid.org.yaml
  - helm-rendered.yaml
  - telegraf-servicemonitor.yml
