---
resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 5Mi

serviceMonitor:
  enabled: true
  labels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}
