---
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

daemonset:
  nodeSelector:
    feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: "false"

serviceMonitor:
  enabled: true
  labels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}
