---
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

serviceMonitor:
  enabled: true
  labels:
    {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}

networkPolicy:
  enabled: true
