---
setDefaultUser:
  enabled: true
  user:
    username: {{ OPMON_influxdb.admin_username }}
    password: {{ OPMON_influxdb.admin_password }}

env: {{ OPMON_influxdb.env | tojson }}

persistence:
  enabled: true
  size: 8Gi # this size is guess work

securityContext:
  runAsUser: 1999
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions: # try to schedule away from Kafka
          - key: "strimzi.io/cluster"
            operator: In
            values:
            - "{{ dunedaq.kafka.name }}"
        topologyKey: kubernetes.io/hostname
