apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "trust-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "trust-manager.labels" . | indent 4 }}
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "trust-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "trust-manager.labels" . | indent 4 }}
spec:
  dnsNames:
  - "{{ include "trust-manager.name" . }}.{{ .Release.Namespace }}.svc"
  secretName: {{ include "trust-manager.name" . }}-tls
  revisionHistoryLimit: 1
  issuerRef:
    name: {{ include "trust-manager.name" . }}
    kind: Issuer
    group: cert-manager.io

---

{{- if .Values.app.webhook.tls.approverPolicy.enabled -}}

apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: trust-manager-policy
  namespace: {{ .Release.Namespace }}
spec:
  allowed:
    dnsNames:
      values: ["{{ include "trust-manager.name" . }}.{{ .Release.Namespace }}.svc"]
      required: true
  selector:
    issuerRef:
      name: {{ include "trust-manager.name" . }}
      kind: Issuer
      group: cert-manager.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trust-manager-policy-role
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    resourceNames: ["trust-manager-policy"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trust-manager-policy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trust-manager-policy-role
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: {{ .Values.app.webhook.tls.approverPolicy.certManagerNamespace }}

{{ end }}
