---
deployments:
  - path: namespace
    alwaysDeploy: true

  - barrier: true
    message: We need a namespace to deploy into
    waitReadinessObjects:
      - kind: Namespace

  - path: metrics

  - path: kafka-broker

  - path: kafka-ui

vars:
  - systemEnvVars:
      kafka_hostname: HOSTNAME
  - file: variables/kafka.yaml
