---
deployments:
  - path: namespace
    alwaysDeploy: true

  - path: metrics

  - path: kafka-broker

  - path: kafka-ui

vars:
  - systemEnvVars:
      kafka_hostname: HOSTNAME
  - file: variables/kafka.yaml
