---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dqm
  namespace: kafka
  lables:
    strimzi.io/cluster: {{ dunedaq.kafka.name }}
spec:
  partitions: 1
  replicas: 1
  topicName: DQM
