---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ dunedaq.kafka.name }}
  name: dqm
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
  topicName: DQM
