---
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 16Mi

affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: {{ kubernetes_label.worker }}
         operator: Exists

prometheus:
  monitor:
    enabled: true
    honorLabels: true

extraArgs:
  - --enable-gzip-encoding

networkPolicy:
  enabled: true
  egress:
    - {}

selfMonitor:
  enabled: true
