---
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 32Mi

prometheus:
  monitor:
    enabled: true
    honorLabels: true

extraArgs:
  - --enable-gzip-encoding

networkPolicy:
  enabled: true
  egress:
    - {}

selfMonitor:
  enabled: true
