---
resources: # this is guess work
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 64Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ kubernetes_labels.node_worker }}
              operator: Exists

prometheus:
  monitor:
    enabled: true
    honorLabels: true
    additionalLabels:
      {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}

extraArgs:
  - --enable-gzip-encoding

# enable when:
#   https://github.com/prometheus-community/helm-charts/pull/6274
#   https://github.com/prometheus-community/helm-charts/pull/6402
#   https://github.com/prometheus-community/helm-charts/pull/6302
kubeRBACProxy:
  enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
     requests:
       cpu: 10m
       memory: 32Mi

networkPolicy:
  enabled: true
  egress:  # access to API and DNS
    - ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
      - port: 6443
        protocol: TCP

podDisruptionBudget:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow

selfMonitor:
  enabled: true
