---
resources: # this is guess work
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 64Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ kubernetes_labels.node_worker }}
              operator: Exists

prometheus:
  monitor:
    enabled: true
    honorLabels: true
    additionalLabels:
      {{ prometheus_servicemonitor_label_name }}: {{ prometheus_servicemonitor_labels.system }}

extraArgs:
  - --enable-gzip-encoding

networkPolicy:
  enabled: true
  egress:
    - {}

podDisruptionBudget:
  maxUnavailable: 0
  unhealthyPodEvictionPolicy: AlwaysAllow

selfMonitor:
  enabled: true
