yamlApplicationConfig:
  kafka:
    clusters:
      - name: {{ DUNE_kafka.name }}
        bootstrapServers: {{DUNE_kafka.name }}-kafka-bootstrap:9092
        readOnly: false
#        properties:
#          security.protocol: SASL_PLAINTEXT
#          sasl.mechanism: PLAIN
#          sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="ddd" password="eee";

env:
  - name: DYNAMIC_CONFIG_ENABLED
    value: "true"

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 64Mi

podSecurityContext: # https://github.com/provectus/kafka-ui-charts/pull/10
  fsGroup: 101
securityContext: # https://github.com/provectus/kafka-ui-charts/pull/10
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 100
  seccompProfile:
    type: RuntimeDefault

