---
deployments:
  - path: namespace
    alwaysDeploy: true
    skipDeleteIfTags: true

  - barrier: true

  - path: nfs-subdir-external-provisioner
    skipDeleteIfTags: true

  - barrier: true
    message: wait for nfs-subdir to settle

vars:
    - file: variables/nfs_subdir_external_provisioner.yaml
