---
deployments:
  - path: namespace
    alwaysDeploy: true
    skipDeleteIfTags: true

  - barrier: true

  - path: nfs-subdir-external-provisioner
    skipDeleteIfTags: true

  - barrier: true
    message: wait for nfs-subdir to settle

  - path: nfs-storageclass
