helmChart:
  chartName: prometheus-node-exporter
  chartVersion: 4.30.3
  namespace: '{{ metrics.node_exporter_namespace }}'
  output: helm-rendered.yaml
  releaseName: node-exporter
  repo: https://prometheus-community.github.io/helm-charts
  updateConstraints: ~4.x
