---
resources: # this is guess work
  limits:
    cpu: 500m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector:
  kubernetes.io/os: linux

fullnameOverride: node-exporter

podLabels:
  jobLabel: node-exporter # changing this impacts dashboards

hostPID: true
hostUsers: true # if hostPID is true, hostUsers must be too
{% if target.name == "np04-daq" %}
hostNetwork: true # once we are all kubernetes, drop this
{% endif %}

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1010
  runAsUser: 1010
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

hostSysFsMount:
  mountPropagation: HostToContainer

prometheus:
  podMonitor:
    enabled: true
    attachMetadata:
      node: true
    jobLabel: jobLabel # changing this impacts dashboards
    additionalLabels:
      {{ prometheus_podmonitor_label_name }}: {{ prometheus_podmonitor_labels.system }}
      jobLabel: node-exporter
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name] # ensure consistent node name
        targetLabel: nodename

networkPolicy:
  enabled: true
