helmChart:
  chartVersion: 4.56.3
  namespace: '{{ metrics.node_exporter_namespace }}'
  output: helm-rendered.yaml
  releaseName: node-exporter
  repo: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
