---
automountStorageClass:
  create: true

extraConfigMaps:
  cvmfs-csi-default-local:
    # https://github.com/cvmfs-contrib/cvmfs-csi/issues/158
    default.local: |
      CVMFS_HTTP_PROXY="{{ cvmfs_csi.http_proxy }}"
      CVMFS_QUOTA_LIMIT=1000 # must match .Values.cache.local.cvmfsQuotaLimit
      CVMFS_CACHE_BASE=/cvmfs-localcache # must match .Values.cache.local.location

cache:
  local:
    volumeSpec:
      hostPath:
        path: /var/local-path-provisioner/storageClass-cvmfs.csi.cern.ch/
    cvmfsQuotaLimit: 1000 # TODO: pick a value for this, currently guess work

controllerplugin:
  plugin:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  provisioner:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: {{ kubernetes_labels.node_worker }}
            operator: Exists

nodeplugin:
  automount:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  plugin:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  singlemount:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  registrar:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: {{ kubernetes_labels.node_worker }}
            operator: Exists
