---
cache:
  local:
    cvmfsQuotaLimit: 1000 # TODO: pick a value for this

controllerplugin:
  plugin:
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  provisioner:
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi

nodeplugin:
  plugin:
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  automount:
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  singlemount:
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  registrar:
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
