---
automountStorageClass:
  create: true

cmvfsHttpProxy: "{{ cvmfs_csi.http_proxy }}"

cache:
  local:
    volumeSpec:
      hostPath:
        path: {{ node_local_path_base }}/storageClass-cvmfs.csi.cern.ch/
    cvmfsQuotaLimit: 1000 # TODO: pick a value for this, currently guess work

controllerplugin:
  plugin:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 32Mi
  provisioner:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 32Mi
  networkPolicy:
    enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: {{ kubernetes_labels.node_worker }}
                operator: Exists

nodeplugin:
  automount:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  automountReconciler:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  plugin:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  singlemount:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  registrar:
    resources: # this is guess work
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 16Mi
  networkPolicy:
    enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: {{ kubernetes_labels.node_worker }}
                operator: Exists
